# Supabase Configuration

# Project configuration removed - using local development

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = true
secure_password_change = true

[auth.email.template.invite]
subject = "You have been invited to GASTAT International Dossier System"

[auth.sms]
enable_signup = false
enable_confirmations = true

[auth.sms.test_otp]
code = "123456"

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false