# Supabase Local Development Configuration

[api]
enabled = true
port = 54321
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
port = 54322
major_version = 17

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "25MiB"

[storage.image_transformation]
enabled = true

[inbucket]
enabled = true
port = 54324

[realtime]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = false

[functions]
"intake-tickets" = { verify_jwt = true }
"health-check" = { verify_jwt = false }
"assignments-get" = { verify_jwt = false }