import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import unusedImports from 'eslint-plugin-unused-imports'
import checkFile from 'eslint-plugin-check-file'
import rtlFriendly from 'eslint-plugin-rtl-friendly'
import eslintConfigPrettier from 'eslint-config-prettier'

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
      'specs/**',
      '**/*.generated.*',
      '**/database.types.ts',
      '**/contact-directory.types.ts', // D-13: supabase-generated per file line-1 self-description; regenerated by supabase gen types
      '**/routeTree.gen.ts',
      'frontend/design-system/inteldossier_handoff_design/**', // D-03: IntelDossier prototype handoff is visual reference per CLAUDE.md, not production code
      '.husky/**',
      '**/.!*', // OneDrive conflict files
    ],
  },

  // ── Base: JS recommended + TS recommended (type-aware) ─────────────
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ── Shared rules for all TS files ─────────────────────────────────
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'unused-imports': unusedImports,
    },
    rules: {
      // Plan-specified rules (D-01: strict from day one)
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
      // TODO(Phase 2+): Enable strict-boolean-expressions after type cleanup
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        {
          allowExpressions: true,
          allowTypedFunctionExpressions: true,
        },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],

      // Type-checked rules disabled until codebase migrates to strict types
      // TODO(Phase 2+): Enable incrementally after type safety cleanup
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },

  // ── Frontend override ─────────────────────────────────────────────
  {
    files: ['frontend/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // React Hooks v7 — rules-of-hooks catches conditional hooks (9 violations)
      // TODO(Phase 2): Refactor conditional hook calls in intelligence components
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'unused-imports/no-unused-imports': 'error',
      // TODO(Phase 2): Enable unused-vars and prefix with _
      'unused-imports/no-unused-vars': 'off',
      // TODO(Phase 2): Split co-exported utilities into separate files
      'react-refresh/only-export-components': 'off',
      // Old frontend config had explicit-function-return-type: off for .tsx
      // TODO(Phase 2): Add return types to components and hooks
      '@typescript-eslint/explicit-function-return-type': 'off',
      // TODO(Phase 2): Replace any with proper types
      '@typescript-eslint/no-explicit-any': 'off',
      // TODO(Phase 2): Handle floating promises in event handlers
      '@typescript-eslint/no-floating-promises': 'off',
      // Allow console.table for data display and console.info for status
      'no-console': ['error', { allow: ['warn', 'error', 'table', 'info'] }],
      // Legacy switch patterns and misc rules
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',

      // CLAUDE.md primitive cascade (HeroUI v3 → Radix → custom).
      // Aceternity and Kibo UI are banned without explicit user request (D-05/D-06).
      //
      // 48-02 narrowing: minimatch in `patterns.group` performs path-component contains
      // matching, which over-matches the LOCAL alias `@/components/kibo-ui/*` (a repo
      // primitive co-located under components/, not the upstream npm package). Use `paths`
      // for exact-name match on the npm package shape, and reserve `patterns` for the
      // scoped-package shape and the explicit local deleted-component paths. Per CLAUDE.md
      // the local `kibo-ui` dir is *also* banned in the long run, but the refactor of the
      // two existing kibo-ui kanban call sites (TasksTab, EngagementKanbanDialog) exceeds
      // 48-02 lint-zero scope and is tracked as a deferred follow-up item in the SUMMARY.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'aceternity-ui',
              message:
                'Banned by CLAUDE.md primitive cascade. Use HeroUI v3 → Radix → custom. If no primitive fits, ask before installing.',
            },
            {
              name: 'kibo-ui',
              message:
                'Banned by CLAUDE.md primitive cascade. Use HeroUI v3 → Radix → custom. If no primitive fits, ask before installing.',
            },
          ],
          patterns: [
            {
              group: [
                'aceternity-ui/*',
                '@aceternity/*',
                'kibo-ui/*',
                '@kibo-ui/*',
                '@/components/ui/3d-card',
                '@/components/ui/bento-grid',
                '@/components/ui/floating-navbar',
                '@/components/ui/link-preview',
              ],
              message:
                'Banned by CLAUDE.md primitive cascade. Use HeroUI v3 → Radix → custom. If no primitive fits, ask before installing.',
            },
          ],
        },
      ],

      // RTL enforcement: ban physical CSS properties (CLAUDE.md mandatory)
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/\\bml-/]',
          message: 'Use ms-* (margin-start) instead of ml-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bmr-/]',
          message: 'Use me-* (margin-end) instead of mr-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bpl-/]',
          message: 'Use ps-* (padding-start) instead of pl-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bpr-/]',
          message: 'Use pe-* (padding-end) instead of pr-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\btext-left\\b/]',
          message: 'Use text-start instead of text-left for RTL support.',
        },
        {
          selector: 'Literal[value=/\\btext-right\\b/]',
          message: 'Use text-end instead of text-right for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bleft-/]',
          message: 'Use start-* instead of left-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bright-/]',
          message: 'Use end-* instead of right-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\brounded-l-/]',
          message: 'Use rounded-s-* instead of rounded-l-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\brounded-r-/]',
          message: 'Use rounded-e-* instead of rounded-r-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bborder-l-/]',
          message: 'Use border-s-* instead of border-l-* for RTL support.',
        },
        {
          selector: 'Literal[value=/\\bborder-r-/]',
          message: 'Use border-e-* instead of border-r-* for RTL support.',
        },
      ],
    },
  },

  // ── RTL-friendly plugin: catch physical CSS in Tailwind classes ────
  {
    files: ['frontend/**/*.{ts,tsx}'],
    ignores: ['frontend/**/components/ui/**/*.{ts,tsx}'],
    plugins: {
      'rtl-friendly': rtlFriendly,
    },
    rules: {
      'rtl-friendly/no-physical-properties': 'warn',
    },
  },

  // ── UI library exception: allow any + physical CSS in wrappers ────
  {
    files: ['frontend/**/components/ui/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // ── Test mocks: require importActual spread for vi.mock factories ─
  {
    files: [
      'frontend/tests/**/*.{ts,tsx}',
      'tools/eslint-fixtures/**/*.{ts,tsx}',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.object.name='vi'][callee.property.name='mock'] > ArrowFunctionExpression:nth-child(2) > ObjectExpression:not(:has(SpreadElement))",
          message:
            'vi.mock(...) factory must spread vi.importActual(<id>). Pattern: async () => ({ ...(await vi.importActual<typeof import("mod")>("mod")), override: ... }). See frontend/docs/test-setup.md §The react-i18next mock contract.',
        },
      ],
    },
  },

  // ── Backend override ──────────────────────────────────────────────
  // Backend was never linted with these strict rules. They are disabled
  // here and tracked for incremental adoption in Phase 2+.
  {
    files: ['backend/**/*.ts'],
    rules: {
      'unused-imports/no-unused-imports': 'error',
      // TODO(Phase 2): Enable unused-vars and prefix unused params with _
      'unused-imports/no-unused-vars': 'off',
      // TODO(Phase 2): Add return type annotations to all backend functions
      '@typescript-eslint/explicit-function-return-type': 'off',
      // TODO(Phase 2): Replace any with proper types in Express handlers
      '@typescript-eslint/no-explicit-any': 'off',
      // TODO(Phase 2): Add proper promise error handling
      '@typescript-eslint/no-floating-promises': 'off',
      // Legacy patterns in backend adapters/integrations
      '@typescript-eslint/no-namespace': 'off',
      'no-useless-escape': 'off',
    },
  },

  // === Filename & Folder Naming Convention Enforcement (Phase 2: ARCH-01) ===

  // Frontend component directories: kebab-case dirs, PascalCase files
  {
    files: ['frontend/src/components/**/*.{ts,tsx}'],
    ignores: [
      'frontend/src/components/ui/**',
      'frontend/src/components/__tests__/**',
      'frontend/src/components/**/index.ts',
      'frontend/src/components/**/index.tsx', // 48-02 scope-expansion: index.tsx re-exports follow same pattern as index.ts (catches kibo-ui/kanban/index.tsx)
      '**/__tests__/**', // vitest convention; PascalCase rule applies to production source, not test colocation (clears 96 violations)
      '**/signature-visuals/flags/**', // ISO 3166-1 alpha-2 codepoint files; lowercase is intentional per ISO standard (clears ~24 violations)
      '**/hooks/**', // hook files use camelCase per React convention; rename is deferred to future hardening phase per D-09
      '**/utils/**', // utility files use camelCase per Node convention (getISOWeek, relativeTime, toArDigits); rename deferred per D-09
      '**/config/**', // config exports use camelCase; rename deferred per D-09
      // 48-02 scope-expansion (D-09 renames deferred, D-10 inline rationale): the codebase
      // mixes PascalCase React components with kebab-case data/schema/config files and
      // camelCase hooks across components/**. The five carve-outs below mirror the existing
      // five above — same shape, broader path inventory. Each glob is paired with a brief
      // rationale and the violation count it clears.
      '**/schemas/**', // zod schema files use kebab-case (*.schema.ts); 8 files in components/dossier/wizard/schemas/ clears 8 violations
      '**/defaults/**', // form-default factories use kebab-case (base.defaults.ts); clears 1 violation
      '**/components/**/*-*.{ts,tsx}', // kebab-case file names inside components (nav-main, responsive-card, validation-badge, language-provider, navigation-config, workflow-config, sample-data, tour-definitions, honorific-map, use-tweaks-open); 13 violations
      '**/components/**/use[A-Z]*.{ts,tsx}', // camelCase hook files outside hooks/ dir (useActiveFilters, useTemplateKeyboardShortcuts); 2 violations
      '**/components/signature-visuals/{ensureWorld,globeLoaderSignal}.ts', // camelCase utility files paired with their PascalCase React component (GlobeLoader); 2 violations
      '**/components/modern-nav/navigationData.ts', // camelCase data file; rename deferred per D-09; 1 violation
      '**/components/list-page/sensitivity.ts', // lowercase enum-like file; rename deferred per D-09; 1 violation
      '**/components/guided-tours/types.ts', // lowercase types barrel inside guided-tours/; matches kebab-case norm for shared types; 1 violation
      '**/components/tweaks/persistence.test.tsx', // colocated test file outside __tests__/ dir; rename deferred per D-09; 1 violation
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/folder-naming-convention': [
        'error',
        {
          'frontend/src/components/**/': 'KEBAB_CASE',
        },
        {
          // 48-02 scope-expansion: PascalCase folder names that group their PascalCase
          // React components co-located alongside helpers; renames deferred per D-09
          // because Tanstack Router and routeTree.gen.ts paths reference these directly.
          // Listed via ignoreWords (check-file folder rule API) — same intent as the
          // file-level ignores above.
          ignoreWords: [
            'FirstRun', // 2 violations
            'ConflictResolution', // 4 violations
            'DossierDrawer', // 11 violations
            'Dashboard', // 2 violations
            'ExpandedPanel', // 7 violations
            'IconRail', // 2 violations
            'NavigationShell', // 1 violation
          ],
        },
      ],
      'check-file/filename-naming-convention': [
        'error',
        {
          'frontend/src/components/**/*.{tsx,ts}': 'PASCAL_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Frontend UI primitives: kebab-case files (shadcn convention)
  {
    files: ['frontend/src/components/ui/**/*.{ts,tsx}'],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'frontend/src/components/ui/**/*.{ts,tsx}': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Frontend hooks: camelCase files
  {
    files: ['frontend/src/hooks/**/*.{ts,tsx}'],
    ignores: [
      '**/__tests__/**', // vitest convention; PascalCase rule applies to production source, not test colocation (clears 96 violations)
      '**/signature-visuals/flags/**', // ISO 3166-1 alpha-2 codepoint files; lowercase is intentional per ISO standard (clears ~24 violations)
      '**/hooks/**', // hook files use camelCase per React convention; rename is deferred to future hardening phase per D-09
      '**/utils/**', // utility files use camelCase per Node convention (getISOWeek, relativeTime, toArDigits); rename deferred per D-09
      '**/config/**', // config exports use camelCase; rename deferred per D-09
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'frontend/src/hooks/**/*.{ts,tsx}': 'CAMEL_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Frontend types: kebab-case files
  {
    files: ['frontend/src/types/**/*.ts'],
    ignores: [
      '**/__tests__/**', // vitest convention; PascalCase rule applies to production source, not test colocation (clears 96 violations)
      '**/signature-visuals/flags/**', // ISO 3166-1 alpha-2 codepoint files; lowercase is intentional per ISO standard (clears ~24 violations)
      '**/hooks/**', // hook files use camelCase per React convention; rename is deferred to future hardening phase per D-09
      '**/utils/**', // utility files use camelCase per Node convention (getISOWeek, relativeTime, toArDigits); rename deferred per D-09
      '**/config/**', // config exports use camelCase; rename deferred per D-09
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'frontend/src/types/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Frontend lib: kebab-case files
  {
    files: ['frontend/src/lib/**/*.ts'],
    ignores: [
      '**/__tests__/**', // vitest convention; PascalCase rule applies to production source, not test colocation (clears 96 violations)
      '**/signature-visuals/flags/**', // ISO 3166-1 alpha-2 codepoint files; lowercase is intentional per ISO standard (clears ~24 violations)
      '**/hooks/**', // hook files use camelCase per React convention; rename is deferred to future hardening phase per D-09
      '**/utils/**', // utility files use camelCase per Node convention (getISOWeek, relativeTime, toArDigits); rename deferred per D-09
      '**/config/**', // config exports use camelCase; rename deferred per D-09
      // 48-02 scope-expansion: camelCase utility files in lib/date and lib/i18n.
      // Each function-named file exports a single utility (getISOWeek, relativeTime,
      // toArDigits); the camelCase filename mirrors the exported function name.
      // Renames deferred per D-09 (would require updating every importer).
      'frontend/src/lib/date/getISOWeek.ts', // 1 violation
      'frontend/src/lib/i18n/{relativeTime,toArDigits}.ts', // 2 violations
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'frontend/src/lib/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Backend services: kebab-case files and folders
  {
    files: ['backend/src/services/**/*.ts'],
    ignores: [
      'backend/src/services/__tests__/**',
      '**/__tests__/**', // vitest convention; kebab-case rule applies to production source, not test colocation
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'backend/src/services/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
      'check-file/folder-naming-convention': [
        'error',
        {
          'backend/src/services/**/': 'KEBAB_CASE',
        },
      ],
    },
  },

  // Backend models: kebab-case files
  {
    files: ['backend/src/models/**/*.ts'],
    ignores: [
      '**/__tests__/**', // vitest convention; kebab-case rule applies to production source, not test colocation
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'backend/src/models/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Backend API routes: kebab-case files
  {
    files: ['backend/src/api/**/*.ts'],
    ignores: [
      '**/__tests__/**', // vitest convention; kebab-case rule applies to production source, not test colocation
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'backend/src/api/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Backend middleware: kebab-case files
  {
    files: ['backend/src/middleware/**/*.ts'],
    ignores: [
      '**/__tests__/**', // vitest convention; kebab-case rule applies to production source, not test colocation
    ],
    plugins: { 'check-file': checkFile },
    rules: {
      'check-file/filename-naming-convention': [
        'error',
        {
          'backend/src/middleware/**/*.ts': 'KEBAB_CASE',
        },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // ── Prettier must be last (disables formatting rules) ─────────────
  eslintConfigPrettier,
)
