/**
 * AI Module - Internal Types
 *
 * These types are internal to the AI module.
 * Use the DTOs from core/contracts for inter-module communication.
 *
 * @module ai/types
 */

// ============================================================================
// Internal Entity Types
// ============================================================================

/**
 * Embedding record stored in the database
 */
export interface Embedding {
  id: string
  source_module: string
  source_entity_type: string
  source_entity_id: string
  content_hash: string
  embedding_vector: number[]
  model_version: string
  created_at: string
  updated_at: string
}

/**
 * Brief document generated by AI
 */
export interface Brief {
  id: string
  source_module: string
  source_entity_type: string
  source_entity_id: string
  brief_type: BriefType
  language: 'en' | 'ar'
  summary: string
  key_points: string[]
  sections: BriefSection[]
  sources: BriefSource[]
  confidence_score: number
  model_version: string
  generated_at: string
  expires_at?: string
  is_cached: boolean
}

/**
 * Section within a brief
 */
export interface BriefSection {
  title: string
  title_ar?: string
  content: string
  content_ar?: string
  order: number
}

/**
 * Source reference for brief content
 */
export interface BriefSource {
  type: 'document' | 'engagement' | 'relationship' | 'note'
  entity_id: string
  title: string
  relevance_score: number
}

/**
 * AI recommendation stored in the database
 */
export interface Recommendation {
  id: string
  target_module: string
  target_entity_type: string
  target_entity_id: string
  recommendation_type: RecommendationType
  title: string
  title_ar?: string
  description: string
  description_ar?: string
  confidence: number
  suggested_module?: string
  suggested_entity_type?: string
  suggested_entity_id?: string
  suggested_display_name?: string
  action_url?: string
  metadata?: Record<string, unknown>
  status: 'pending' | 'accepted' | 'dismissed'
  created_at: string
  expires_at?: string
}

/**
 * Extracted entity from text
 */
export interface ExtractedEntityRecord {
  id: string
  source_text_hash: string
  entity_type: ExtractedEntityType
  value: string
  normalized_value?: string
  confidence: number
  position_start: number
  position_end: number
  context?: string
  created_at: string
}

// ============================================================================
// Enums and Constants
// ============================================================================

export type BriefType = 'executive' | 'detailed' | 'quick' | 'talking_points'

export type RecommendationType =
  | 'relationship'
  | 'document'
  | 'action'
  | 'engagement'
  | 'follow_up'
  | 'risk_alert'

export type ExtractedEntityType =
  | 'person'
  | 'organization'
  | 'location'
  | 'date'
  | 'event'
  | 'topic'
  | 'phone'
  | 'email'
  | 'url'

export const BRIEF_TYPE_LABELS: Record<BriefType, { en: string; ar: string }> = {
  executive: { en: 'Executive Summary', ar: 'ملخص تنفيذي' },
  detailed: { en: 'Detailed Brief', ar: 'تقرير مفصل' },
  quick: { en: 'Quick Overview', ar: 'نظرة سريعة' },
  talking_points: { en: 'Talking Points', ar: 'نقاط للحديث' },
}

export const RECOMMENDATION_TYPE_LABELS: Record<RecommendationType, { en: string; ar: string }> = {
  relationship: { en: 'Suggested Relationship', ar: 'علاقة مقترحة' },
  document: { en: 'Related Document', ar: 'مستند ذو صلة' },
  action: { en: 'Recommended Action', ar: 'إجراء موصى به' },
  engagement: { en: 'Engagement Opportunity', ar: 'فرصة مشاركة' },
  follow_up: { en: 'Follow-up Required', ar: 'متابعة مطلوبة' },
  risk_alert: { en: 'Risk Alert', ar: 'تنبيه مخاطر' },
}

export const ENTITY_TYPE_LABELS: Record<ExtractedEntityType, { en: string; ar: string }> = {
  person: { en: 'Person', ar: 'شخص' },
  organization: { en: 'Organization', ar: 'منظمة' },
  location: { en: 'Location', ar: 'موقع' },
  date: { en: 'Date', ar: 'تاريخ' },
  event: { en: 'Event', ar: 'حدث' },
  topic: { en: 'Topic', ar: 'موضوع' },
  phone: { en: 'Phone', ar: 'هاتف' },
  email: { en: 'Email', ar: 'بريد إلكتروني' },
  url: { en: 'URL', ar: 'رابط' },
}

// ============================================================================
// Request Types
// ============================================================================

export interface EmbeddingGenerationRequest {
  text: string
  moduleId: string
  entityType: string
  entityId: string
}

export interface SemanticSearchRequest {
  query: string
  modules?: string[]
  entityTypes?: string[]
  limit?: number
  threshold?: number
}

export interface BriefGenerationRequest {
  moduleId: string
  entityType: string
  entityId: string
  briefType: BriefType
  language: 'en' | 'ar'
  includeRelationships?: boolean
  includeDocuments?: boolean
  includeTimeline?: boolean
  maxLength?: number
}

export interface EntityExtractionRequest {
  text: string
  entityTypes?: ExtractedEntityType[]
}

export interface RecommendationRequest {
  moduleId: string
  entityType: string
  entityId: string
  types?: RecommendationType[]
  limit?: number
}

// ============================================================================
// Response Types
// ============================================================================

export interface SemanticSearchResponse {
  results: Array<{
    moduleId: string
    entityType: string
    entityId: string
    score: number
    snippet: string
    highlights?: string[]
  }>
  total: number
  searchTime: number
}

export interface EntityExtractionResponse {
  entities: Array<{
    type: ExtractedEntityType
    value: string
    confidence: number
    position: { start: number; end: number }
  }>
  processingTime: number
}

// ============================================================================
// Configuration
// ============================================================================

export interface AIModuleConfig {
  embeddingModel: string
  embeddingDimensions: number
  llmModel: string
  maxTokens: number
  temperature: number
  cacheEnabled: boolean
  cacheTTL: number
  batchSize: number
}

export const DEFAULT_AI_CONFIG: AIModuleConfig = {
  embeddingModel: 'bge-m3',
  embeddingDimensions: 1536,
  llmModel: 'gpt-4',
  maxTokens: 4096,
  temperature: 0.7,
  cacheEnabled: true,
  cacheTTL: 3600, // 1 hour
  batchSize: 10,
}
