#!/bin/bash

# Script to copy country maps from source to frontend public assets
# Maps country names to ISO codes and creates elegant background images

SOURCE_DIR="/Users/khalidalzahrani/Library/CloudStorage/OneDrive-Personal/coding/maps"
DEST_DIR="/Users/khalidalzahrani/Library/CloudStorage/OneDrive-Personal/coding/Intl-DossierV2.0/frontend/public/assets/maps"

# Create destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

# Counter for copied files
count=0

# Map filename to ISO code
# This associative array maps the exact filename (without .svg) to ISO code
declare -A map_to_iso=(
  # GCC Countries
  ["Saudi Arabia"]="sa"
  ["UnitedArabEmirates"]="ae"
  ["Kuwait"]="kw"
  ["Qatar"]="qa"
  ["Bahrain"]="bh"
  ["Oman"]="om"

  # Middle East
  ["Egypt"]="eg"
  ["Jordan"]="jo"
  ["Lebanon"]="lb"
  ["Syria"]="sy"
  ["Iraq"]="iq"
  ["Palestine"]="ps"
  ["Israel"]="il"
  ["Yemen"]="ye"
  ["Iran"]="ir"
  ["Turkey"]="tr"

  # North Africa
  ["Morocco"]="ma"
  ["Algeria"]="dz"
  ["Tunisia"]="tn"
  ["Libya"]="ly"
  ["Sudan"]="sd"
  ["Mauritania"]="mr"

  # Asia
  ["China"]="cn"
  ["Japan"]="jp"
  ["SouthKorea"]="kr"
  ["South Korea"]="kr"
  ["NorthKorea"]="kp"
  ["North Korea"]="kp"
  ["India"]="in"
  ["Pakistan"]="pk"
  ["Bangladesh"]="bd"
  ["Indonesia"]="id"
  ["Malaysia"]="my"
  ["Singapore"]="sg"
  ["Thailand"]="th"
  ["Vietnam"]="vn"
  ["Philippines"]="ph"

  # Europe
  ["United Kingdom"]="gb"
  ["France"]="fr"
  ["Germany"]="de"
  ["Italy"]="it"
  ["Spain"]="es"
  ["Netherlands"]="nl"
  ["Belgium"]="be"
  ["Switzerland"]="ch"
  ["Austria"]="at"
  ["Sweden"]="se"
  ["Norway"]="no"
  ["Denmark"]="dk"
  ["Finland"]="fi"
  ["Poland"]="pl"
  ["Russia"]="ru"
  ["Ukraine"]="ua"
  ["Greece"]="gr"
  ["Portugal"]="pt"
  ["CzechRepublic"]="cz"
  ["Czech Republic"]="cz"

  # Americas
  ["UnitedStatesofAmerica"]="us"
  ["United States"]="us"
  ["Canada"]="ca"
  ["Mexico"]="mx"
  ["Brazil"]="br"
  ["Argentina"]="ar"
  ["Chile"]="cl"
  ["Colombia"]="co"
  ["Peru"]="pe"

  # Oceania
  ["Australia"]="au"
  ["NewZealand"]="nz"
  ["New Zealand"]="nz"

  # Additional countries
  ["Afghanistan"]="af"
  ["Albania"]="al"
  ["Andorra"]="ad"
  ["Angola"]="ao"
  ["Anguilla"]="ai"
  ["Antigua Barbuda"]="ag"
  ["Armenia"]="am"
  ["Aruba"]="aw"
  ["Azerbaijan"]="az"
  ["Bahamas"]="bs"
  ["Barbados"]="bb"
  ["Belarus"]="by"
  ["Belize"]="bz"
  ["Benin"]="bj"
  ["Bermuda"]="bm"
  ["Bhutan"]="bt"
  ["Bolivia"]="bo"
  ["Bosnia Herzegovina"]="ba"
  ["Botswana"]="bw"
  ["Brunei"]="bn"
  ["Bulgaria"]="bg"
  ["BurkinaFaso"]="bf"
  ["Burundi"]="bi"
  ["Cambodia"]="kh"
  ["Cameroon"]="cm"
  ["CapeVerde"]="cv"
  ["CaymanIslands"]="ky"
  ["CentralAfricanRepublic"]="cf"
  ["Chad"]="td"
  ["Comoros"]="km"
  ["DRCongo"]="cd"
  ["RepublicCongo"]="cg"
  ["CostaRica"]="cr"
  ["Croatia"]="hr"
  ["Cuba"]="cu"
  ["Cyprus"]="cy"
  ["Djibouti"]="dj"
  ["Dominica"]="dm"
  ["DominicanRepublic"]="do"
  ["Ecuador"]="ec"
  ["ElSalvador"]="sv"
  ["EquatorialGuinea"]="gq"
  ["Eritrea"]="er"
  ["Estonia"]="ee"
  ["Eswatini"]="sz"
  ["Ethiopia"]="et"
  ["Fiji"]="fj"
  ["Gabon"]="ga"
  ["Gambia"]="gm"
  ["Georgia"]="ge"
  ["Ghana"]="gh"
  ["Grenada"]="gd"
  ["Guatemala"]="gt"
  ["Guinea"]="gn"
  ["GuineaBissau"]="gw"
  ["Guyana"]="gy"
  ["Haiti"]="ht"
  ["Honduras"]="hn"
  ["Hungary"]="hu"
  ["Iceland"]="is"
  ["Ireland"]="ie"
  ["IvoryCoast"]="ci"
  ["Jamaica"]="jm"
  ["Kazakhstan"]="kz"
  ["Kenya"]="ke"
  ["Kiribati"]="ki"
  ["Kosovo"]="xk"
  ["Kyrgyzstan"]="kg"
  ["Laos"]="la"
  ["Latvia"]="lv"
  ["Lesotho"]="ls"
  ["Liberia"]="lr"
  ["Liechtenstein"]="li"
  ["Lithuania"]="lt"
  ["Luxembourg"]="lu"
  ["Madagascar"]="mg"
  ["Malawi"]="mw"
  ["Maldives"]="mv"
  ["Mali"]="ml"
  ["Malta"]="mt"
  ["MarshallIslands"]="mh"
  ["Mauritius"]="mu"
  ["Micronesia"]="fm"
  ["Moldova"]="md"
  ["Monaco"]="mc"
  ["Mongolia"]="mn"
  ["Montenegro"]="me"
  ["Montserrat"]="ms"
  ["Mozambique"]="mz"
  ["Myanmar"]="mm"
  ["Namibia"]="na"
  ["Nauru"]="nr"
  ["Nepal"]="np"
  ["Nicaragua"]="ni"
  ["Niger"]="ne"
  ["Nigeria"]="ng"
  ["NorthMacedonia"]="mk"
  ["Palau"]="pw"
  ["Panama"]="pa"
  ["PapuaNewGuinea"]="pg"
  ["Paraguay"]="py"
  ["Romania"]="ro"
  ["Rwanda"]="rw"
  ["SaintKitts Nevis"]="kn"
  ["SaintLucia"]="lc"
  ["SaintVincent Grenadines"]="vc"
  ["Samoa"]="ws"
  ["SanMarino"]="sm"
  ["SaoTome Principe"]="st"
  ["Senegal"]="sn"
  ["Serbia"]="rs"
  ["Seychelles"]="sc"
  ["SierraLeone"]="sl"
  ["Slovakia"]="sk"
  ["Slovenia"]="si"
  ["SolomonIslands"]="sb"
  ["Somalia"]="so"
  ["SouthAfrica"]="za"
  ["SouthSudan"]="ss"
  ["SriLanka"]="lk"
  ["Suriname"]="sr"
  ["Taiwan"]="tw"
  ["Tajikistan"]="tj"
  ["Tanzania"]="tz"
  ["TimorLeste"]="tl"
  ["Togo"]="tg"
  ["Tonga"]="to"
  ["TrinidadTobago"]="tt"
  ["Turkmenistan"]="tm"
  ["Tuvalu"]="tv"
  ["Uganda"]="ug"
  ["Uruguay"]="uy"
  ["Uzbekistan"]="uz"
  ["Vanuatu"]="vu"
  ["VaticanCity"]="va"
  ["Venezuela"]="ve"
  ["Zambia"]="zm"
  ["Zimbabwe"]="zw"
  ["AmericanSamoa"]="as"
)

# Copy and rename files
for file in "$SOURCE_DIR"/*.svg; do
  [ -f "$file" ] || continue

  # Get the base filename without extension
  filename=$(basename "$file" .svg)

  # Check if we have a mapping for this filename
  if [ -n "${map_to_iso[$filename]}" ]; then
    iso_code="${map_to_iso[$filename]}"
    cp "$file" "$DEST_DIR/${iso_code}.svg"
    ((count++))
    echo "✓ $filename → ${iso_code}.svg"
  else
    echo "⚠ Skipped: $filename (no ISO mapping)"
  fi
done

echo ""
echo "✅ Copied $count country map files to $DEST_DIR"
echo "📁 Files are named as: sa.svg, us.svg, cn.svg, etc."
echo "🗺️  Country maps ready for use as elegant card backgrounds"
