openapi: 3.1.0
info:
  title: Dossier CRUD API
  description: |
    Unified CRUD operations for all dossier types (country, organization, forum, engagement, theme, working_group, person).
    Implements Class Table Inheritance pattern with polymorphic responses.
  version: 1.0.0
  contact:
    name: Intl-Dossier API Team
    email: api@intl-dossier.local

servers:
  - url: https://zkrcjzdemdmwhearhfgg.supabase.co/functions/v1
    description: Supabase Edge Functions (Production)
  - url: http://localhost:54321/functions/v1
    description: Local Development

security:
  - bearerAuth: []

paths:
  /dossiers:
    get:
      summary: List dossiers
      description: Retrieve paginated list of dossiers with optional filtering by type, status, and search query
      operationId: listDossiers
      tags:
        - Dossiers
      parameters:
        - name: type
          in: query
          description: Filter by dossier type
          schema:
            $ref: '#/components/schemas/DossierType'
        - name: status
          in: query
          description: Filter by status
          schema:
            $ref: '#/components/schemas/DossierStatus'
        - name: search
          in: query
          description: Full-text search query
          schema:
            type: string
            minLength: 2
            maxLength: 100
        - name: limit
          in: query
          description: Number of results per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of results to skip (pagination)
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - pagination
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DossierSummary'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Create dossier
      description: Create new dossier with type-specific extension data
      operationId: createDossier
      tags:
        - Dossiers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DossierCreate'
      responses:
        '201':
          description: Dossier created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DossierDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'

  /dossiers/{id}:
    get:
      summary: Get dossier by ID
      description: Retrieve single dossier with type-specific extension data
      operationId: getDossier
      tags:
        - Dossiers
      parameters:
        - $ref: '#/components/parameters/DossierId'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DossierDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    patch:
      summary: Update dossier
      description: Update dossier base fields and/or type-specific extension data
      operationId: updateDossier
      tags:
        - Dossiers
      parameters:
        - $ref: '#/components/parameters/DossierId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DossierUpdate'
      responses:
        '200':
          description: Dossier updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DossierDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Delete dossier (soft delete)
      description: Mark dossier as deleted (status='deleted'). Cascade deletes extension data.
      operationId: deleteDossier
      tags:
        - Dossiers
      parameters:
        - $ref: '#/components/parameters/DossierId'
      responses:
        '204':
          description: Dossier deleted successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase Auth JWT token

  parameters:
    DossierId:
      name: id
      in: path
      required: true
      description: Dossier UUID
      schema:
        type: string
        format: uuid

  schemas:
    DossierType:
      type: string
      enum:
        - country
        - organization
        - forum
        - engagement
        - theme
        - working_group
        - person
      description: Type of dossier entity

    DossierStatus:
      type: string
      enum:
        - active
        - inactive
        - archived
        - deleted
      default: active
      description: Status of dossier entity

    SensitivityLevel:
      type: integer
      minimum: 1
      maximum: 4
      default: 1
      description: Clearance level required (1=Public, 2=Internal, 3=Confidential, 4=Secret)

    DossierBase:
      type: object
      required:
        - type
        - name_en
        - name_ar
      properties:
        type:
          $ref: '#/components/schemas/DossierType'
        name_en:
          type: string
          minLength: 1
          maxLength: 255
          description: Name in English
        name_ar:
          type: string
          minLength: 1
          maxLength: 255
          description: Name in Arabic
        description_en:
          type: string
          maxLength: 5000
          description: Description in English
        description_ar:
          type: string
          maxLength: 5000
          description: Description in Arabic
        status:
          $ref: '#/components/schemas/DossierStatus'
        sensitivity_level:
          $ref: '#/components/schemas/SensitivityLevel'
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 20
          description: Searchable tags
        metadata:
          type: object
          additionalProperties: true
          description: Flexible JSONB metadata

    DossierSummary:
      allOf:
        - $ref: '#/components/schemas/DossierBase'
        - type: object
          required:
            - id
            - created_at
            - updated_at
          properties:
            id:
              type: string
              format: uuid
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time

    DossierDetail:
      allOf:
        - $ref: '#/components/schemas/DossierSummary'
        - type: object
          properties:
            created_by:
              type: string
              format: uuid
              description: User ID who created
            updated_by:
              type: string
              format: uuid
              description: User ID who last updated
            extension_data:
              oneOf:
                - $ref: '#/components/schemas/CountryExtension'
                - $ref: '#/components/schemas/OrganizationExtension'
                - $ref: '#/components/schemas/ForumExtension'
                - $ref: '#/components/schemas/EngagementExtension'
                - $ref: '#/components/schemas/ThemeExtension'
                - $ref: '#/components/schemas/WorkingGroupExtension'
                - $ref: '#/components/schemas/PersonExtension'
              discriminator:
                propertyName: type
                mapping:
                  country: '#/components/schemas/CountryExtension'
                  organization: '#/components/schemas/OrganizationExtension'
                  forum: '#/components/schemas/ForumExtension'
                  engagement: '#/components/schemas/EngagementExtension'
                  theme: '#/components/schemas/ThemeExtension'
                  working_group: '#/components/schemas/WorkingGroupExtension'
                  person: '#/components/schemas/PersonExtension'
              description: Type-specific extension data

    DossierCreate:
      allOf:
        - $ref: '#/components/schemas/DossierBase'
        - type: object
          properties:
            extension_data:
              oneOf:
                - $ref: '#/components/schemas/CountryExtension'
                - $ref: '#/components/schemas/OrganizationExtension'
                - $ref: '#/components/schemas/ForumExtension'
                - $ref: '#/components/schemas/EngagementExtension'
                - $ref: '#/components/schemas/ThemeExtension'
                - $ref: '#/components/schemas/WorkingGroupExtension'
                - $ref: '#/components/schemas/PersonExtension'
              discriminator:
                propertyName: type
              description: Type-specific extension data (required for creation)

    DossierUpdate:
      type: object
      properties:
        name_en:
          type: string
          minLength: 1
          maxLength: 255
        name_ar:
          type: string
          minLength: 1
          maxLength: 255
        description_en:
          type: string
          maxLength: 5000
        description_ar:
          type: string
          maxLength: 5000
        status:
          $ref: '#/components/schemas/DossierStatus'
        sensitivity_level:
          $ref: '#/components/schemas/SensitivityLevel'
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 20
        metadata:
          type: object
          additionalProperties: true
        extension_data:
          type: object
          description: Partial update to extension data (merged with existing)
          additionalProperties: true

    CountryExtension:
      type: object
      required:
        - iso_code_2
        - iso_code_3
      properties:
        iso_code_2:
          type: string
          pattern: '^[A-Z]{2}$'
          description: ISO 3166-1 alpha-2 code
        iso_code_3:
          type: string
          pattern: '^[A-Z]{3}$'
          description: ISO 3166-1 alpha-3 code
        capital_en:
          type: string
          maxLength: 100
        capital_ar:
          type: string
          maxLength: 100
        region:
          type: string
          maxLength: 50
        subregion:
          type: string
          maxLength: 50
        population:
          type: integer
          minimum: 0
        area_sq_km:
          type: number
          minimum: 0
        flag_url:
          type: string
          format: uri
          maxLength: 500

    OrganizationExtension:
      type: object
      required:
        - org_type
      properties:
        org_code:
          type: string
          maxLength: 50
        org_type:
          type: string
          enum:
            - government
            - ngo
            - private
            - international
            - academic
        headquarters_country_id:
          type: string
          format: uuid
          description: Country where org is based
        parent_org_id:
          type: string
          format: uuid
          description: Parent organization (for hierarchy)
        website:
          type: string
          format: uri
          maxLength: 500
        email:
          type: string
          format: email
          maxLength: 255
        phone:
          type: string
          maxLength: 50
        address_en:
          type: string
          maxLength: 500
        address_ar:
          type: string
          maxLength: 500
        logo_url:
          type: string
          format: uri
          maxLength: 500
        established_date:
          type: string
          format: date

    ForumExtension:
      type: object
      properties:
        number_of_sessions:
          type: integer
          minimum: 1
        keynote_speakers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              title:
                type: string
              organization:
                type: string
        sponsors:
          type: array
          items:
            type: object
            additionalProperties: true
        registration_fee:
          type: number
          minimum: 0
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          description: ISO 4217 currency code
        agenda_url:
          type: string
          format: uri
          maxLength: 500
        live_stream_url:
          type: string
          format: uri
          maxLength: 500

    EngagementExtension:
      type: object
      required:
        - engagement_type
        - engagement_category
      properties:
        engagement_type:
          type: string
          enum:
            - meeting
            - consultation
            - coordination
            - workshop
            - conference
            - site_visit
            - ceremony
        engagement_category:
          type: string
          enum:
            - bilateral
            - multilateral
            - regional
            - internal
        location_en:
          type: string
          maxLength: 255
        location_ar:
          type: string
          maxLength: 255

    ThemeExtension:
      type: object
      required:
        - theme_category
      properties:
        theme_category:
          type: string
          enum:
            - policy
            - technical
            - strategic
            - operational
        parent_theme_id:
          type: string
          format: uuid
          description: Parent theme (for thematic hierarchy)

    WorkingGroupExtension:
      type: object
      properties:
        mandate_en:
          type: string
          maxLength: 2000
        mandate_ar:
          type: string
          maxLength: 2000
        lead_org_id:
          type: string
          format: uuid
          description: Organization leading the working group
        wg_status:
          type: string
          enum:
            - active
            - suspended
            - disbanded
          default: active
        established_date:
          type: string
          format: date
        disbandment_date:
          type: string
          format: date

    PersonExtension:
      type: object
      properties:
        title_en:
          type: string
          maxLength: 255
        title_ar:
          type: string
          maxLength: 255
        organization_id:
          type: string
          format: uuid
          description: Current organization affiliation
        nationality_country_id:
          type: string
          format: uuid
          description: Country of nationality
        email:
          type: string
          format: email
          maxLength: 255
        phone:
          type: string
          maxLength: 50
        biography_en:
          type: string
          maxLength: 5000
        biography_ar:
          type: string
          maxLength: 5000
        photo_url:
          type: string
          format: uri
          maxLength: 500

    Pagination:
      type: object
      required:
        - total
        - limit
        - offset
      properties:
        total:
          type: integer
          minimum: 0
          description: Total number of results
        limit:
          type: integer
          minimum: 1
          description: Results per page
        offset:
          type: integer
          minimum: 0
          description: Results skipped
        has_more:
          type: boolean
          description: Whether more results exist

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error context

  responses:
    BadRequest:
      description: Bad request (invalid parameters)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: 'VALIDATION_ERROR'
            message: 'Invalid dossier type provided'

    Unauthorized:
      description: Unauthorized (missing or invalid authentication)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: 'UNAUTHORIZED'
            message: 'Authentication required'

    Forbidden:
      description: Forbidden (insufficient clearance level)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: 'FORBIDDEN'
            message: 'Insufficient clearance level to access this dossier'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: 'NOT_FOUND'
            message: 'Dossier not found'

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: 'INTERNAL_ERROR'
            message: 'An unexpected error occurred'
