openapi: 3.1.0
info:
  title: Unified Search API
  description: Full-text search across all dossier types with ranked results
  version: 1.0.0

servers:
  - url: https://zkrcjzdemdmwhearhfgg.supabase.co/functions/v1
  - url: http://localhost:54321/functions/v1

security:
  - bearerAuth: []

paths:
  /search:
    get:
      summary: Search dossiers
      description: Full-text search with ranking across all entity types
      operationId: searchDossiers
      tags:
        - Search
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
            minLength: 2
        - name: type
          in: query
          description: Filter by dossier type
          schema:
            type: string
            enum: [country, organization, forum, engagement, theme, working_group, person]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        type:
                          type: string
                        name_en:
                          type: string
                        name_ar:
                          type: string
                        rank:
                          type: number
                          description: Relevance score
                        snippet:
                          type: string
                          description: Highlighted excerpt
                  pagination:
                    type: object

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
