openapi: 3.0.3
info:
  title: Engagement Kanban Board API
  version: 1.0.0
  description: |
    API endpoints for the Engagement Kanban Board feature, supporting real-time collaboration,
    role-based stage transitions, and dual SLA tracking.

servers:
  - url: https://zkrcjzdemdmwhearhfgg.supabase.co/functions/v1
    description: Supabase Edge Functions (Staging)

security:
  - bearerAuth: []

paths:
  /engagements-kanban-get/{engagementId}:
    get:
      summary: Get Kanban board data for an engagement
      description: |
        Fetches all assignments for a specific engagement grouped by workflow stage,
        with optional sorting within each column.
      operationId: getEngagementKanban
      tags:
        - Kanban
      parameters:
        - name: engagementId
          in: path
          required: true
          description: UUID of the engagement
          schema:
            type: string
            format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        - name: sort
          in: query
          required: false
          description: Sort order for assignments within each column
          schema:
            type: string
            enum: [created_at, sla_deadline, priority]
            default: created_at
          example: "sla_deadline"
      responses:
        '200':
          description: Kanban board data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KanbanBoardResponse'
              example:
                columns:
                  todo:
                    - id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                      title: "Review contract terms"
                      assignee:
                        id: "11111111-2222-3333-4444-555555555555"
                        name: "Ahmed Al-Zahrani"
                        avatar_url: "https://example.com/avatar.jpg"
                      priority: "high"
                      overall_sla_deadline: "2025-10-10T12:00:00Z"
                      current_stage_sla_deadline: "2025-10-08T12:00:00Z"
                      created_at: "2025-10-07T08:00:00Z"
                  in_progress:
                    - id: "b2c3d4e5-f6a7-8901-bcde-f12345678901"
                      title: "Prepare briefing pack"
                      assignee:
                        id: "22222222-3333-4444-5555-666666666666"
                        name: "Fatima Al-Mutairi"
                        avatar_url: null
                      priority: "medium"
                      overall_sla_deadline: "2025-10-12T12:00:00Z"
                      current_stage_sla_deadline: "2025-10-09T12:00:00Z"
                      created_at: "2025-10-06T10:00:00Z"
                  review: []
                  done: []
                  cancelled: []
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /assignments-workflow-stage-update/{assignmentId}:
    patch:
      summary: Update assignment workflow stage
      description: |
        Updates the workflow stage of an assignment with role-based validation,
        SLA tracking, and real-time broadcast to other users viewing the Kanban board.
      operationId: updateAssignmentWorkflowStage
      tags:
        - Kanban
      parameters:
        - name: assignmentId
          in: path
          required: true
          description: UUID of the assignment to update
          schema:
            type: string
            format: uuid
          example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkflowStageRequest'
            example:
              workflow_stage: "in_progress"
              triggered_by_user_id: "11111111-2222-3333-4444-555555555555"
      responses:
        '200':
          description: Assignment workflow stage updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWorkflowStageResponse'
              example:
                success: true
                assignment:
                  id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                  workflow_stage: "in_progress"
                  current_stage_sla_deadline: "2025-10-09T12:00:00Z"
                  updated_at: "2025-10-07T14:30:00Z"
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "Invalid workflow_stage value"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Forbidden - Role-based validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWorkflowStageResponse'
              example:
                success: false
                validation_error: "Staff members must move assignments through stages sequentially. Cannot skip from 'todo' to 'done'."
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token from auth.session().access_token

  schemas:
    KanbanBoardResponse:
      type: object
      properties:
        columns:
          type: object
          properties:
            todo:
              type: array
              items:
                $ref: '#/components/schemas/AssignmentCard'
            in_progress:
              type: array
              items:
                $ref: '#/components/schemas/AssignmentCard'
            review:
              type: array
              items:
                $ref: '#/components/schemas/AssignmentCard'
            done:
              type: array
              items:
                $ref: '#/components/schemas/AssignmentCard'
            cancelled:
              type: array
              items:
                $ref: '#/components/schemas/AssignmentCard'
      required:
        - columns

    AssignmentCard:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Assignment unique identifier
        title:
          type: string
          description: Assignment title
        assignee:
          $ref: '#/components/schemas/AssigneeInfo'
        priority:
          type: string
          enum: [high, medium, low]
          description: Priority level
        overall_sla_deadline:
          type: string
          format: date-time
          nullable: true
          description: Overall assignment SLA deadline (creation to completion)
        current_stage_sla_deadline:
          type: string
          format: date-time
          nullable: true
          description: Current workflow stage SLA deadline
        created_at:
          type: string
          format: date-time
          description: Assignment creation timestamp
      required:
        - id
        - title
        - priority
        - created_at

    AssigneeInfo:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
          description: Staff profile ID
        name:
          type: string
          description: Staff member full name
        avatar_url:
          type: string
          format: uri
          nullable: true
          description: Avatar image URL
      required:
        - id
        - name

    UpdateWorkflowStageRequest:
      type: object
      properties:
        workflow_stage:
          type: string
          enum: [todo, in_progress, review, done, cancelled]
          description: New workflow stage
        triggered_by_user_id:
          type: string
          format: uuid
          description: ID of the user triggering the stage change
      required:
        - workflow_stage
        - triggered_by_user_id

    UpdateWorkflowStageResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the update succeeded
        assignment:
          type: object
          nullable: true
          description: Updated assignment data (present on success)
          properties:
            id:
              type: string
              format: uuid
            workflow_stage:
              type: string
              enum: [todo, in_progress, review, done, cancelled]
            current_stage_sla_deadline:
              type: string
              format: date-time
              nullable: true
            updated_at:
              type: string
              format: date-time
        validation_error:
          type: string
          nullable: true
          description: Human-readable validation error message (present on 403)
      required:
        - success

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
      required:
        - success
        - error

  responses:
    Unauthorized:
      description: Unauthorized - Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Unauthorized"

    Forbidden:
      description: Forbidden - User lacks permissions to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Forbidden"

    NotFound:
      description: Not Found - Resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Engagement not found"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Internal server error"

tags:
  - name: Kanban
    description: Engagement Kanban board operations
