/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ModernNavStandaloneRouteImport } from './routes/modern-nav-standalone'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedWorkingGroupsRouteImport } from './routes/_protected/working-groups'
import { Route as ProtectedWordAssistantRouteImport } from './routes/_protected/word-assistant'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedThemesRouteImport } from './routes/_protected/themes'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSearchRouteImport } from './routes/_protected/search'
import { Route as ProtectedResponsiveDemoRouteImport } from './routes/_protected/responsive-demo'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedPrototypeDossierRouteImport } from './routes/_protected/prototype-dossier'
import { Route as ProtectedPositionsRouteImport } from './routes/_protected/positions'
import { Route as ProtectedPersonsRouteImport } from './routes/_protected/persons'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected/organizations'
import { Route as ProtectedMousRouteImport } from './routes/_protected/mous'
import { Route as ProtectedMonitoringRouteImport } from './routes/_protected/monitoring'
import { Route as ProtectedModernNavDemoRouteImport } from './routes/_protected/modern-nav-demo'
import { Route as ProtectedIntelligenceRouteImport } from './routes/_protected/intelligence'
import { Route as ProtectedIntakeRouteImport } from './routes/_protected/intake'
import { Route as ProtectedHelpRouteImport } from './routes/_protected/help'
import { Route as ProtectedForumsRouteImport } from './routes/_protected/forums'
import { Route as ProtectedExportRouteImport } from './routes/_protected/export'
import { Route as ProtectedEventsRouteImport } from './routes/_protected/events'
import { Route as ProtectedDataLibraryRouteImport } from './routes/_protected/data-library'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCountriesRouteImport } from './routes/_protected/countries'
import { Route as ProtectedContactsRouteImport } from './routes/_protected/contacts'
import { Route as ProtectedCalendarRouteImport } from './routes/_protected/calendar'
import { Route as ProtectedBriefsRouteImport } from './routes/_protected/briefs'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as ProtectedAccessibilityRouteImport } from './routes/_protected/accessibility'
import { Route as ProtectedTasksIndexRouteImport } from './routes/_protected/tasks/index'
import { Route as ProtectedPositionsIndexRouteImport } from './routes/_protected/positions/index'
import { Route as ProtectedIntakeIndexRouteImport } from './routes/_protected/intake/index'
import { Route as ProtectedEngagementsIndexRouteImport } from './routes/_protected/engagements/index'
import { Route as ProtectedDossiersIndexRouteImport } from './routes/_protected/dossiers/index'
import { Route as ProtectedApprovalsIndexRouteImport } from './routes/_protected/approvals/index'
import { Route as ProtectedAfterActionsIndexRouteImport } from './routes/_protected/after-actions/index'
import { Route as ProtectedTasksQueueRouteImport } from './routes/_protected/tasks/queue'
import { Route as ProtectedTasksEscalationsRouteImport } from './routes/_protected/tasks/escalations'
import { Route as ProtectedTasksIdRouteImport } from './routes/_protected/tasks/$id'
import { Route as ProtectedRelationshipsGraphRouteImport } from './routes/_protected/relationships/graph'
import { Route as ProtectedPositionsPositionIdRouteImport } from './routes/_protected/positions/$positionId'
import { Route as ProtectedPositionsIdRouteImport } from './routes/_protected/positions/$id'
import { Route as ProtectedMyWorkWaitingRouteImport } from './routes/_protected/my-work/waiting'
import { Route as ProtectedMyWorkIntakeRouteImport } from './routes/_protected/my-work/intake'
import { Route as ProtectedMyWorkAssignmentsRouteImport } from './routes/_protected/my-work/assignments'
import { Route as ProtectedIntakeQueueRouteImport } from './routes/_protected/intake/queue'
import { Route as ProtectedIntakeNewRouteImport } from './routes/_protected/intake/new'
import { Route as ProtectedEngagementsEngagementIdRouteImport } from './routes/_protected/engagements/$engagementId'
import { Route as ProtectedDossiersIdRouteImport } from './routes/_protected/dossiers/$id'
import { Route as ProtectedContactsNotesSearchRouteImport } from './routes/_protected/contacts/notes-search'
import { Route as ProtectedContactsCreateRouteImport } from './routes/_protected/contacts/create'
import { Route as ProtectedContactsContactIdRouteImport } from './routes/_protected/contacts/$contactId'
import { Route as ProtectedCalendarNewRouteImport } from './routes/_protected/calendar/new'
import { Route as ProtectedAfterActionsAfterActionIdRouteImport } from './routes/_protected/after-actions/$afterActionId'
import { Route as ProtectedAdminApprovalsRouteImport } from './routes/_protected/admin/approvals'
import { Route as ProtectedPositionsIdVersionsRouteImport } from './routes/_protected/positions/$id/versions'
import { Route as ProtectedPositionsIdApprovalsRouteImport } from './routes/_protected/positions/$id/approvals'
import { Route as ProtectedIntakeTicketsIdRouteImport } from './routes/_protected/intake/tickets.$id'
import { Route as ProtectedEngagementsEngagementIdAfterActionRouteImport } from './routes/_protected/engagements/$engagementId/after-action'
import { Route as ProtectedAfterActionsAfterActionIdVersionsRouteImport } from './routes/_protected/after-actions/$afterActionId/versions'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernNavStandaloneRoute = ModernNavStandaloneRouteImport.update({
  id: '/modern-nav-standalone',
  path: '/modern-nav-standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkingGroupsRoute = ProtectedWorkingGroupsRouteImport.update({
  id: '/working-groups',
  path: '/working-groups',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWordAssistantRoute = ProtectedWordAssistantRouteImport.update({
  id: '/word-assistant',
  path: '/word-assistant',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedThemesRoute = ProtectedThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSearchRoute = ProtectedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedResponsiveDemoRoute = ProtectedResponsiveDemoRouteImport.update({
  id: '/responsive-demo',
  path: '/responsive-demo',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPrototypeDossierRoute =
  ProtectedPrototypeDossierRouteImport.update({
    id: '/prototype-dossier',
    path: '/prototype-dossier',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPositionsRoute = ProtectedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPersonsRoute = ProtectedPersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMousRoute = ProtectedMousRouteImport.update({
  id: '/mous',
  path: '/mous',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMonitoringRoute = ProtectedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedModernNavDemoRoute = ProtectedModernNavDemoRouteImport.update({
  id: '/modern-nav-demo',
  path: '/modern-nav-demo',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIntelligenceRoute = ProtectedIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIntakeRoute = ProtectedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedForumsRoute = ProtectedForumsRouteImport.update({
  id: '/forums',
  path: '/forums',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExportRoute = ProtectedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventsRoute = ProtectedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDataLibraryRoute = ProtectedDataLibraryRouteImport.update({
  id: '/data-library',
  path: '/data-library',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCountriesRoute = ProtectedCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContactsRoute = ProtectedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCalendarRoute = ProtectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBriefsRoute = ProtectedBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccessibilityRoute = ProtectedAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTasksIndexRoute = ProtectedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPositionsIndexRoute = ProtectedPositionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPositionsRoute,
} as any)
const ProtectedIntakeIndexRoute = ProtectedIntakeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedIntakeRoute,
} as any)
const ProtectedEngagementsIndexRoute =
  ProtectedEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDossiersIndexRoute = ProtectedDossiersIndexRouteImport.update({
  id: '/dossiers/',
  path: '/dossiers/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApprovalsIndexRoute = ProtectedApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAfterActionsIndexRoute =
  ProtectedAfterActionsIndexRouteImport.update({
    id: '/after-actions/',
    path: '/after-actions/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTasksQueueRoute = ProtectedTasksQueueRouteImport.update({
  id: '/tasks/queue',
  path: '/tasks/queue',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTasksEscalationsRoute =
  ProtectedTasksEscalationsRouteImport.update({
    id: '/tasks/escalations',
    path: '/tasks/escalations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTasksIdRoute = ProtectedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRelationshipsGraphRoute =
  ProtectedRelationshipsGraphRouteImport.update({
    id: '/relationships/graph',
    path: '/relationships/graph',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPositionsPositionIdRoute =
  ProtectedPositionsPositionIdRouteImport.update({
    id: '/$positionId',
    path: '/$positionId',
    getParentRoute: () => ProtectedPositionsRoute,
  } as any)
const ProtectedPositionsIdRoute = ProtectedPositionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtectedPositionsRoute,
} as any)
const ProtectedMyWorkWaitingRoute = ProtectedMyWorkWaitingRouteImport.update({
  id: '/my-work/waiting',
  path: '/my-work/waiting',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyWorkIntakeRoute = ProtectedMyWorkIntakeRouteImport.update({
  id: '/my-work/intake',
  path: '/my-work/intake',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyWorkAssignmentsRoute =
  ProtectedMyWorkAssignmentsRouteImport.update({
    id: '/my-work/assignments',
    path: '/my-work/assignments',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedIntakeQueueRoute = ProtectedIntakeQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ProtectedIntakeRoute,
} as any)
const ProtectedIntakeNewRoute = ProtectedIntakeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedIntakeRoute,
} as any)
const ProtectedEngagementsEngagementIdRoute =
  ProtectedEngagementsEngagementIdRouteImport.update({
    id: '/engagements/$engagementId',
    path: '/engagements/$engagementId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDossiersIdRoute = ProtectedDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContactsNotesSearchRoute =
  ProtectedContactsNotesSearchRouteImport.update({
    id: '/notes-search',
    path: '/notes-search',
    getParentRoute: () => ProtectedContactsRoute,
  } as any)
const ProtectedContactsCreateRoute = ProtectedContactsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProtectedContactsRoute,
} as any)
const ProtectedContactsContactIdRoute =
  ProtectedContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => ProtectedContactsRoute,
  } as any)
const ProtectedCalendarNewRoute = ProtectedCalendarNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedCalendarRoute,
} as any)
const ProtectedAfterActionsAfterActionIdRoute =
  ProtectedAfterActionsAfterActionIdRouteImport.update({
    id: '/after-actions/$afterActionId',
    path: '/after-actions/$afterActionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminApprovalsRoute = ProtectedAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPositionsIdVersionsRoute =
  ProtectedPositionsIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ProtectedPositionsIdRoute,
  } as any)
const ProtectedPositionsIdApprovalsRoute =
  ProtectedPositionsIdApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => ProtectedPositionsIdRoute,
  } as any)
const ProtectedIntakeTicketsIdRoute =
  ProtectedIntakeTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => ProtectedIntakeRoute,
  } as any)
const ProtectedEngagementsEngagementIdAfterActionRoute =
  ProtectedEngagementsEngagementIdAfterActionRouteImport.update({
    id: '/after-action',
    path: '/after-action',
    getParentRoute: () => ProtectedEngagementsEngagementIdRoute,
  } as any)
const ProtectedAfterActionsAfterActionIdVersionsRoute =
  ProtectedAfterActionsAfterActionIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ProtectedAfterActionsAfterActionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/modern-nav-standalone': typeof ModernNavStandaloneRoute
  '/register': typeof RegisterRoute
  '/accessibility': typeof ProtectedAccessibilityRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/briefs': typeof ProtectedBriefsRoute
  '/calendar': typeof ProtectedCalendarRouteWithChildren
  '/contacts': typeof ProtectedContactsRouteWithChildren
  '/countries': typeof ProtectedCountriesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/data-library': typeof ProtectedDataLibraryRoute
  '/events': typeof ProtectedEventsRoute
  '/export': typeof ProtectedExportRoute
  '/forums': typeof ProtectedForumsRoute
  '/help': typeof ProtectedHelpRoute
  '/intake': typeof ProtectedIntakeRouteWithChildren
  '/intelligence': typeof ProtectedIntelligenceRoute
  '/modern-nav-demo': typeof ProtectedModernNavDemoRoute
  '/monitoring': typeof ProtectedMonitoringRoute
  '/mous': typeof ProtectedMousRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/persons': typeof ProtectedPersonsRoute
  '/positions': typeof ProtectedPositionsRouteWithChildren
  '/prototype-dossier': typeof ProtectedPrototypeDossierRoute
  '/reports': typeof ProtectedReportsRoute
  '/responsive-demo': typeof ProtectedResponsiveDemoRoute
  '/search': typeof ProtectedSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/themes': typeof ProtectedThemesRoute
  '/users': typeof ProtectedUsersRoute
  '/word-assistant': typeof ProtectedWordAssistantRoute
  '/working-groups': typeof ProtectedWorkingGroupsRoute
  '/admin/approvals': typeof ProtectedAdminApprovalsRoute
  '/after-actions/$afterActionId': typeof ProtectedAfterActionsAfterActionIdRouteWithChildren
  '/calendar/new': typeof ProtectedCalendarNewRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/contacts/create': typeof ProtectedContactsCreateRoute
  '/contacts/notes-search': typeof ProtectedContactsNotesSearchRoute
  '/dossiers/$id': typeof ProtectedDossiersIdRoute
  '/engagements/$engagementId': typeof ProtectedEngagementsEngagementIdRouteWithChildren
  '/intake/new': typeof ProtectedIntakeNewRoute
  '/intake/queue': typeof ProtectedIntakeQueueRoute
  '/my-work/assignments': typeof ProtectedMyWorkAssignmentsRoute
  '/my-work/intake': typeof ProtectedMyWorkIntakeRoute
  '/my-work/waiting': typeof ProtectedMyWorkWaitingRoute
  '/positions/$id': typeof ProtectedPositionsIdRouteWithChildren
  '/positions/$positionId': typeof ProtectedPositionsPositionIdRoute
  '/relationships/graph': typeof ProtectedRelationshipsGraphRoute
  '/tasks/$id': typeof ProtectedTasksIdRoute
  '/tasks/escalations': typeof ProtectedTasksEscalationsRoute
  '/tasks/queue': typeof ProtectedTasksQueueRoute
  '/after-actions': typeof ProtectedAfterActionsIndexRoute
  '/approvals': typeof ProtectedApprovalsIndexRoute
  '/dossiers': typeof ProtectedDossiersIndexRoute
  '/engagements': typeof ProtectedEngagementsIndexRoute
  '/intake/': typeof ProtectedIntakeIndexRoute
  '/positions/': typeof ProtectedPositionsIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/after-actions/$afterActionId/versions': typeof ProtectedAfterActionsAfterActionIdVersionsRoute
  '/engagements/$engagementId/after-action': typeof ProtectedEngagementsEngagementIdAfterActionRoute
  '/intake/tickets/$id': typeof ProtectedIntakeTicketsIdRoute
  '/positions/$id/approvals': typeof ProtectedPositionsIdApprovalsRoute
  '/positions/$id/versions': typeof ProtectedPositionsIdVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/modern-nav-standalone': typeof ModernNavStandaloneRoute
  '/register': typeof RegisterRoute
  '/accessibility': typeof ProtectedAccessibilityRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/briefs': typeof ProtectedBriefsRoute
  '/calendar': typeof ProtectedCalendarRouteWithChildren
  '/contacts': typeof ProtectedContactsRouteWithChildren
  '/countries': typeof ProtectedCountriesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/data-library': typeof ProtectedDataLibraryRoute
  '/events': typeof ProtectedEventsRoute
  '/export': typeof ProtectedExportRoute
  '/forums': typeof ProtectedForumsRoute
  '/help': typeof ProtectedHelpRoute
  '/intelligence': typeof ProtectedIntelligenceRoute
  '/modern-nav-demo': typeof ProtectedModernNavDemoRoute
  '/monitoring': typeof ProtectedMonitoringRoute
  '/mous': typeof ProtectedMousRoute
  '/organizations': typeof ProtectedOrganizationsRoute
  '/persons': typeof ProtectedPersonsRoute
  '/prototype-dossier': typeof ProtectedPrototypeDossierRoute
  '/reports': typeof ProtectedReportsRoute
  '/responsive-demo': typeof ProtectedResponsiveDemoRoute
  '/search': typeof ProtectedSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/themes': typeof ProtectedThemesRoute
  '/users': typeof ProtectedUsersRoute
  '/word-assistant': typeof ProtectedWordAssistantRoute
  '/working-groups': typeof ProtectedWorkingGroupsRoute
  '/admin/approvals': typeof ProtectedAdminApprovalsRoute
  '/after-actions/$afterActionId': typeof ProtectedAfterActionsAfterActionIdRouteWithChildren
  '/calendar/new': typeof ProtectedCalendarNewRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/contacts/create': typeof ProtectedContactsCreateRoute
  '/contacts/notes-search': typeof ProtectedContactsNotesSearchRoute
  '/dossiers/$id': typeof ProtectedDossiersIdRoute
  '/engagements/$engagementId': typeof ProtectedEngagementsEngagementIdRouteWithChildren
  '/intake/new': typeof ProtectedIntakeNewRoute
  '/intake/queue': typeof ProtectedIntakeQueueRoute
  '/my-work/assignments': typeof ProtectedMyWorkAssignmentsRoute
  '/my-work/intake': typeof ProtectedMyWorkIntakeRoute
  '/my-work/waiting': typeof ProtectedMyWorkWaitingRoute
  '/positions/$id': typeof ProtectedPositionsIdRouteWithChildren
  '/positions/$positionId': typeof ProtectedPositionsPositionIdRoute
  '/relationships/graph': typeof ProtectedRelationshipsGraphRoute
  '/tasks/$id': typeof ProtectedTasksIdRoute
  '/tasks/escalations': typeof ProtectedTasksEscalationsRoute
  '/tasks/queue': typeof ProtectedTasksQueueRoute
  '/after-actions': typeof ProtectedAfterActionsIndexRoute
  '/approvals': typeof ProtectedApprovalsIndexRoute
  '/dossiers': typeof ProtectedDossiersIndexRoute
  '/engagements': typeof ProtectedEngagementsIndexRoute
  '/intake': typeof ProtectedIntakeIndexRoute
  '/positions': typeof ProtectedPositionsIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/after-actions/$afterActionId/versions': typeof ProtectedAfterActionsAfterActionIdVersionsRoute
  '/engagements/$engagementId/after-action': typeof ProtectedEngagementsEngagementIdAfterActionRoute
  '/intake/tickets/$id': typeof ProtectedIntakeTicketsIdRoute
  '/positions/$id/approvals': typeof ProtectedPositionsIdApprovalsRoute
  '/positions/$id/versions': typeof ProtectedPositionsIdVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/modern-nav-standalone': typeof ModernNavStandaloneRoute
  '/register': typeof RegisterRoute
  '/_protected/accessibility': typeof ProtectedAccessibilityRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/briefs': typeof ProtectedBriefsRoute
  '/_protected/calendar': typeof ProtectedCalendarRouteWithChildren
  '/_protected/contacts': typeof ProtectedContactsRouteWithChildren
  '/_protected/countries': typeof ProtectedCountriesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/data-library': typeof ProtectedDataLibraryRoute
  '/_protected/events': typeof ProtectedEventsRoute
  '/_protected/export': typeof ProtectedExportRoute
  '/_protected/forums': typeof ProtectedForumsRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/intake': typeof ProtectedIntakeRouteWithChildren
  '/_protected/intelligence': typeof ProtectedIntelligenceRoute
  '/_protected/modern-nav-demo': typeof ProtectedModernNavDemoRoute
  '/_protected/monitoring': typeof ProtectedMonitoringRoute
  '/_protected/mous': typeof ProtectedMousRoute
  '/_protected/organizations': typeof ProtectedOrganizationsRoute
  '/_protected/persons': typeof ProtectedPersonsRoute
  '/_protected/positions': typeof ProtectedPositionsRouteWithChildren
  '/_protected/prototype-dossier': typeof ProtectedPrototypeDossierRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/responsive-demo': typeof ProtectedResponsiveDemoRoute
  '/_protected/search': typeof ProtectedSearchRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/themes': typeof ProtectedThemesRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/word-assistant': typeof ProtectedWordAssistantRoute
  '/_protected/working-groups': typeof ProtectedWorkingGroupsRoute
  '/_protected/admin/approvals': typeof ProtectedAdminApprovalsRoute
  '/_protected/after-actions/$afterActionId': typeof ProtectedAfterActionsAfterActionIdRouteWithChildren
  '/_protected/calendar/new': typeof ProtectedCalendarNewRoute
  '/_protected/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/_protected/contacts/create': typeof ProtectedContactsCreateRoute
  '/_protected/contacts/notes-search': typeof ProtectedContactsNotesSearchRoute
  '/_protected/dossiers/$id': typeof ProtectedDossiersIdRoute
  '/_protected/engagements/$engagementId': typeof ProtectedEngagementsEngagementIdRouteWithChildren
  '/_protected/intake/new': typeof ProtectedIntakeNewRoute
  '/_protected/intake/queue': typeof ProtectedIntakeQueueRoute
  '/_protected/my-work/assignments': typeof ProtectedMyWorkAssignmentsRoute
  '/_protected/my-work/intake': typeof ProtectedMyWorkIntakeRoute
  '/_protected/my-work/waiting': typeof ProtectedMyWorkWaitingRoute
  '/_protected/positions/$id': typeof ProtectedPositionsIdRouteWithChildren
  '/_protected/positions/$positionId': typeof ProtectedPositionsPositionIdRoute
  '/_protected/relationships/graph': typeof ProtectedRelationshipsGraphRoute
  '/_protected/tasks/$id': typeof ProtectedTasksIdRoute
  '/_protected/tasks/escalations': typeof ProtectedTasksEscalationsRoute
  '/_protected/tasks/queue': typeof ProtectedTasksQueueRoute
  '/_protected/after-actions/': typeof ProtectedAfterActionsIndexRoute
  '/_protected/approvals/': typeof ProtectedApprovalsIndexRoute
  '/_protected/dossiers/': typeof ProtectedDossiersIndexRoute
  '/_protected/engagements/': typeof ProtectedEngagementsIndexRoute
  '/_protected/intake/': typeof ProtectedIntakeIndexRoute
  '/_protected/positions/': typeof ProtectedPositionsIndexRoute
  '/_protected/tasks/': typeof ProtectedTasksIndexRoute
  '/_protected/after-actions/$afterActionId/versions': typeof ProtectedAfterActionsAfterActionIdVersionsRoute
  '/_protected/engagements/$engagementId/after-action': typeof ProtectedEngagementsEngagementIdAfterActionRoute
  '/_protected/intake/tickets/$id': typeof ProtectedIntakeTicketsIdRoute
  '/_protected/positions/$id/approvals': typeof ProtectedPositionsIdApprovalsRoute
  '/_protected/positions/$id/versions': typeof ProtectedPositionsIdVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/modern-nav-standalone'
    | '/register'
    | '/accessibility'
    | '/analytics'
    | '/briefs'
    | '/calendar'
    | '/contacts'
    | '/countries'
    | '/dashboard'
    | '/data-library'
    | '/events'
    | '/export'
    | '/forums'
    | '/help'
    | '/intake'
    | '/intelligence'
    | '/modern-nav-demo'
    | '/monitoring'
    | '/mous'
    | '/organizations'
    | '/persons'
    | '/positions'
    | '/prototype-dossier'
    | '/reports'
    | '/responsive-demo'
    | '/search'
    | '/settings'
    | '/themes'
    | '/users'
    | '/word-assistant'
    | '/working-groups'
    | '/admin/approvals'
    | '/after-actions/$afterActionId'
    | '/calendar/new'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts/notes-search'
    | '/dossiers/$id'
    | '/engagements/$engagementId'
    | '/intake/new'
    | '/intake/queue'
    | '/my-work/assignments'
    | '/my-work/intake'
    | '/my-work/waiting'
    | '/positions/$id'
    | '/positions/$positionId'
    | '/relationships/graph'
    | '/tasks/$id'
    | '/tasks/escalations'
    | '/tasks/queue'
    | '/after-actions'
    | '/approvals'
    | '/dossiers'
    | '/engagements'
    | '/intake/'
    | '/positions/'
    | '/tasks'
    | '/after-actions/$afterActionId/versions'
    | '/engagements/$engagementId/after-action'
    | '/intake/tickets/$id'
    | '/positions/$id/approvals'
    | '/positions/$id/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/modern-nav-standalone'
    | '/register'
    | '/accessibility'
    | '/analytics'
    | '/briefs'
    | '/calendar'
    | '/contacts'
    | '/countries'
    | '/dashboard'
    | '/data-library'
    | '/events'
    | '/export'
    | '/forums'
    | '/help'
    | '/intelligence'
    | '/modern-nav-demo'
    | '/monitoring'
    | '/mous'
    | '/organizations'
    | '/persons'
    | '/prototype-dossier'
    | '/reports'
    | '/responsive-demo'
    | '/search'
    | '/settings'
    | '/themes'
    | '/users'
    | '/word-assistant'
    | '/working-groups'
    | '/admin/approvals'
    | '/after-actions/$afterActionId'
    | '/calendar/new'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts/notes-search'
    | '/dossiers/$id'
    | '/engagements/$engagementId'
    | '/intake/new'
    | '/intake/queue'
    | '/my-work/assignments'
    | '/my-work/intake'
    | '/my-work/waiting'
    | '/positions/$id'
    | '/positions/$positionId'
    | '/relationships/graph'
    | '/tasks/$id'
    | '/tasks/escalations'
    | '/tasks/queue'
    | '/after-actions'
    | '/approvals'
    | '/dossiers'
    | '/engagements'
    | '/intake'
    | '/positions'
    | '/tasks'
    | '/after-actions/$afterActionId/versions'
    | '/engagements/$engagementId/after-action'
    | '/intake/tickets/$id'
    | '/positions/$id/approvals'
    | '/positions/$id/versions'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/modern-nav-standalone'
    | '/register'
    | '/_protected/accessibility'
    | '/_protected/analytics'
    | '/_protected/briefs'
    | '/_protected/calendar'
    | '/_protected/contacts'
    | '/_protected/countries'
    | '/_protected/dashboard'
    | '/_protected/data-library'
    | '/_protected/events'
    | '/_protected/export'
    | '/_protected/forums'
    | '/_protected/help'
    | '/_protected/intake'
    | '/_protected/intelligence'
    | '/_protected/modern-nav-demo'
    | '/_protected/monitoring'
    | '/_protected/mous'
    | '/_protected/organizations'
    | '/_protected/persons'
    | '/_protected/positions'
    | '/_protected/prototype-dossier'
    | '/_protected/reports'
    | '/_protected/responsive-demo'
    | '/_protected/search'
    | '/_protected/settings'
    | '/_protected/themes'
    | '/_protected/users'
    | '/_protected/word-assistant'
    | '/_protected/working-groups'
    | '/_protected/admin/approvals'
    | '/_protected/after-actions/$afterActionId'
    | '/_protected/calendar/new'
    | '/_protected/contacts/$contactId'
    | '/_protected/contacts/create'
    | '/_protected/contacts/notes-search'
    | '/_protected/dossiers/$id'
    | '/_protected/engagements/$engagementId'
    | '/_protected/intake/new'
    | '/_protected/intake/queue'
    | '/_protected/my-work/assignments'
    | '/_protected/my-work/intake'
    | '/_protected/my-work/waiting'
    | '/_protected/positions/$id'
    | '/_protected/positions/$positionId'
    | '/_protected/relationships/graph'
    | '/_protected/tasks/$id'
    | '/_protected/tasks/escalations'
    | '/_protected/tasks/queue'
    | '/_protected/after-actions/'
    | '/_protected/approvals/'
    | '/_protected/dossiers/'
    | '/_protected/engagements/'
    | '/_protected/intake/'
    | '/_protected/positions/'
    | '/_protected/tasks/'
    | '/_protected/after-actions/$afterActionId/versions'
    | '/_protected/engagements/$engagementId/after-action'
    | '/_protected/intake/tickets/$id'
    | '/_protected/positions/$id/approvals'
    | '/_protected/positions/$id/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModernNavStandaloneRoute: typeof ModernNavStandaloneRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern-nav-standalone': {
      id: '/modern-nav-standalone'
      path: '/modern-nav-standalone'
      fullPath: '/modern-nav-standalone'
      preLoaderRoute: typeof ModernNavStandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/working-groups': {
      id: '/_protected/working-groups'
      path: '/working-groups'
      fullPath: '/working-groups'
      preLoaderRoute: typeof ProtectedWorkingGroupsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/word-assistant': {
      id: '/_protected/word-assistant'
      path: '/word-assistant'
      fullPath: '/word-assistant'
      preLoaderRoute: typeof ProtectedWordAssistantRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/themes': {
      id: '/_protected/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ProtectedThemesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/responsive-demo': {
      id: '/_protected/responsive-demo'
      path: '/responsive-demo'
      fullPath: '/responsive-demo'
      preLoaderRoute: typeof ProtectedResponsiveDemoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/prototype-dossier': {
      id: '/_protected/prototype-dossier'
      path: '/prototype-dossier'
      fullPath: '/prototype-dossier'
      preLoaderRoute: typeof ProtectedPrototypeDossierRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/positions': {
      id: '/_protected/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof ProtectedPositionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/persons': {
      id: '/_protected/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof ProtectedPersonsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mous': {
      id: '/_protected/mous'
      path: '/mous'
      fullPath: '/mous'
      preLoaderRoute: typeof ProtectedMousRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/monitoring': {
      id: '/_protected/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof ProtectedMonitoringRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/modern-nav-demo': {
      id: '/_protected/modern-nav-demo'
      path: '/modern-nav-demo'
      fullPath: '/modern-nav-demo'
      preLoaderRoute: typeof ProtectedModernNavDemoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/intelligence': {
      id: '/_protected/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof ProtectedIntelligenceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/intake': {
      id: '/_protected/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof ProtectedIntakeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forums': {
      id: '/_protected/forums'
      path: '/forums'
      fullPath: '/forums'
      preLoaderRoute: typeof ProtectedForumsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/export': {
      id: '/_protected/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ProtectedExportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/events': {
      id: '/_protected/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof ProtectedEventsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/data-library': {
      id: '/_protected/data-library'
      path: '/data-library'
      fullPath: '/data-library'
      preLoaderRoute: typeof ProtectedDataLibraryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/countries': {
      id: '/_protected/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof ProtectedCountriesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts': {
      id: '/_protected/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ProtectedContactsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/calendar': {
      id: '/_protected/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ProtectedCalendarRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/briefs': {
      id: '/_protected/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof ProtectedBriefsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/accessibility': {
      id: '/_protected/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof ProtectedAccessibilityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tasks/': {
      id: '/_protected/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ProtectedTasksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/positions/': {
      id: '/_protected/positions/'
      path: '/'
      fullPath: '/positions/'
      preLoaderRoute: typeof ProtectedPositionsIndexRouteImport
      parentRoute: typeof ProtectedPositionsRoute
    }
    '/_protected/intake/': {
      id: '/_protected/intake/'
      path: '/'
      fullPath: '/intake/'
      preLoaderRoute: typeof ProtectedIntakeIndexRouteImport
      parentRoute: typeof ProtectedIntakeRoute
    }
    '/_protected/engagements/': {
      id: '/_protected/engagements/'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof ProtectedEngagementsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dossiers/': {
      id: '/_protected/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof ProtectedDossiersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/approvals/': {
      id: '/_protected/approvals/'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ProtectedApprovalsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/after-actions/': {
      id: '/_protected/after-actions/'
      path: '/after-actions'
      fullPath: '/after-actions'
      preLoaderRoute: typeof ProtectedAfterActionsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tasks/queue': {
      id: '/_protected/tasks/queue'
      path: '/tasks/queue'
      fullPath: '/tasks/queue'
      preLoaderRoute: typeof ProtectedTasksQueueRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tasks/escalations': {
      id: '/_protected/tasks/escalations'
      path: '/tasks/escalations'
      fullPath: '/tasks/escalations'
      preLoaderRoute: typeof ProtectedTasksEscalationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tasks/$id': {
      id: '/_protected/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof ProtectedTasksIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/relationships/graph': {
      id: '/_protected/relationships/graph'
      path: '/relationships/graph'
      fullPath: '/relationships/graph'
      preLoaderRoute: typeof ProtectedRelationshipsGraphRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/positions/$positionId': {
      id: '/_protected/positions/$positionId'
      path: '/$positionId'
      fullPath: '/positions/$positionId'
      preLoaderRoute: typeof ProtectedPositionsPositionIdRouteImport
      parentRoute: typeof ProtectedPositionsRoute
    }
    '/_protected/positions/$id': {
      id: '/_protected/positions/$id'
      path: '/$id'
      fullPath: '/positions/$id'
      preLoaderRoute: typeof ProtectedPositionsIdRouteImport
      parentRoute: typeof ProtectedPositionsRoute
    }
    '/_protected/my-work/waiting': {
      id: '/_protected/my-work/waiting'
      path: '/my-work/waiting'
      fullPath: '/my-work/waiting'
      preLoaderRoute: typeof ProtectedMyWorkWaitingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-work/intake': {
      id: '/_protected/my-work/intake'
      path: '/my-work/intake'
      fullPath: '/my-work/intake'
      preLoaderRoute: typeof ProtectedMyWorkIntakeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-work/assignments': {
      id: '/_protected/my-work/assignments'
      path: '/my-work/assignments'
      fullPath: '/my-work/assignments'
      preLoaderRoute: typeof ProtectedMyWorkAssignmentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/intake/queue': {
      id: '/_protected/intake/queue'
      path: '/queue'
      fullPath: '/intake/queue'
      preLoaderRoute: typeof ProtectedIntakeQueueRouteImport
      parentRoute: typeof ProtectedIntakeRoute
    }
    '/_protected/intake/new': {
      id: '/_protected/intake/new'
      path: '/new'
      fullPath: '/intake/new'
      preLoaderRoute: typeof ProtectedIntakeNewRouteImport
      parentRoute: typeof ProtectedIntakeRoute
    }
    '/_protected/engagements/$engagementId': {
      id: '/_protected/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof ProtectedEngagementsEngagementIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dossiers/$id': {
      id: '/_protected/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof ProtectedDossiersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/notes-search': {
      id: '/_protected/contacts/notes-search'
      path: '/notes-search'
      fullPath: '/contacts/notes-search'
      preLoaderRoute: typeof ProtectedContactsNotesSearchRouteImport
      parentRoute: typeof ProtectedContactsRoute
    }
    '/_protected/contacts/create': {
      id: '/_protected/contacts/create'
      path: '/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ProtectedContactsCreateRouteImport
      parentRoute: typeof ProtectedContactsRoute
    }
    '/_protected/contacts/$contactId': {
      id: '/_protected/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ProtectedContactsContactIdRouteImport
      parentRoute: typeof ProtectedContactsRoute
    }
    '/_protected/calendar/new': {
      id: '/_protected/calendar/new'
      path: '/new'
      fullPath: '/calendar/new'
      preLoaderRoute: typeof ProtectedCalendarNewRouteImport
      parentRoute: typeof ProtectedCalendarRoute
    }
    '/_protected/after-actions/$afterActionId': {
      id: '/_protected/after-actions/$afterActionId'
      path: '/after-actions/$afterActionId'
      fullPath: '/after-actions/$afterActionId'
      preLoaderRoute: typeof ProtectedAfterActionsAfterActionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/approvals': {
      id: '/_protected/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof ProtectedAdminApprovalsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/positions/$id/versions': {
      id: '/_protected/positions/$id/versions'
      path: '/versions'
      fullPath: '/positions/$id/versions'
      preLoaderRoute: typeof ProtectedPositionsIdVersionsRouteImport
      parentRoute: typeof ProtectedPositionsIdRoute
    }
    '/_protected/positions/$id/approvals': {
      id: '/_protected/positions/$id/approvals'
      path: '/approvals'
      fullPath: '/positions/$id/approvals'
      preLoaderRoute: typeof ProtectedPositionsIdApprovalsRouteImport
      parentRoute: typeof ProtectedPositionsIdRoute
    }
    '/_protected/intake/tickets/$id': {
      id: '/_protected/intake/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/intake/tickets/$id'
      preLoaderRoute: typeof ProtectedIntakeTicketsIdRouteImport
      parentRoute: typeof ProtectedIntakeRoute
    }
    '/_protected/engagements/$engagementId/after-action': {
      id: '/_protected/engagements/$engagementId/after-action'
      path: '/after-action'
      fullPath: '/engagements/$engagementId/after-action'
      preLoaderRoute: typeof ProtectedEngagementsEngagementIdAfterActionRouteImport
      parentRoute: typeof ProtectedEngagementsEngagementIdRoute
    }
    '/_protected/after-actions/$afterActionId/versions': {
      id: '/_protected/after-actions/$afterActionId/versions'
      path: '/versions'
      fullPath: '/after-actions/$afterActionId/versions'
      preLoaderRoute: typeof ProtectedAfterActionsAfterActionIdVersionsRouteImport
      parentRoute: typeof ProtectedAfterActionsAfterActionIdRoute
    }
  }
}

interface ProtectedCalendarRouteChildren {
  ProtectedCalendarNewRoute: typeof ProtectedCalendarNewRoute
}

const ProtectedCalendarRouteChildren: ProtectedCalendarRouteChildren = {
  ProtectedCalendarNewRoute: ProtectedCalendarNewRoute,
}

const ProtectedCalendarRouteWithChildren =
  ProtectedCalendarRoute._addFileChildren(ProtectedCalendarRouteChildren)

interface ProtectedContactsRouteChildren {
  ProtectedContactsContactIdRoute: typeof ProtectedContactsContactIdRoute
  ProtectedContactsCreateRoute: typeof ProtectedContactsCreateRoute
  ProtectedContactsNotesSearchRoute: typeof ProtectedContactsNotesSearchRoute
}

const ProtectedContactsRouteChildren: ProtectedContactsRouteChildren = {
  ProtectedContactsContactIdRoute: ProtectedContactsContactIdRoute,
  ProtectedContactsCreateRoute: ProtectedContactsCreateRoute,
  ProtectedContactsNotesSearchRoute: ProtectedContactsNotesSearchRoute,
}

const ProtectedContactsRouteWithChildren =
  ProtectedContactsRoute._addFileChildren(ProtectedContactsRouteChildren)

interface ProtectedIntakeRouteChildren {
  ProtectedIntakeNewRoute: typeof ProtectedIntakeNewRoute
  ProtectedIntakeQueueRoute: typeof ProtectedIntakeQueueRoute
  ProtectedIntakeIndexRoute: typeof ProtectedIntakeIndexRoute
  ProtectedIntakeTicketsIdRoute: typeof ProtectedIntakeTicketsIdRoute
}

const ProtectedIntakeRouteChildren: ProtectedIntakeRouteChildren = {
  ProtectedIntakeNewRoute: ProtectedIntakeNewRoute,
  ProtectedIntakeQueueRoute: ProtectedIntakeQueueRoute,
  ProtectedIntakeIndexRoute: ProtectedIntakeIndexRoute,
  ProtectedIntakeTicketsIdRoute: ProtectedIntakeTicketsIdRoute,
}

const ProtectedIntakeRouteWithChildren = ProtectedIntakeRoute._addFileChildren(
  ProtectedIntakeRouteChildren,
)

interface ProtectedPositionsIdRouteChildren {
  ProtectedPositionsIdApprovalsRoute: typeof ProtectedPositionsIdApprovalsRoute
  ProtectedPositionsIdVersionsRoute: typeof ProtectedPositionsIdVersionsRoute
}

const ProtectedPositionsIdRouteChildren: ProtectedPositionsIdRouteChildren = {
  ProtectedPositionsIdApprovalsRoute: ProtectedPositionsIdApprovalsRoute,
  ProtectedPositionsIdVersionsRoute: ProtectedPositionsIdVersionsRoute,
}

const ProtectedPositionsIdRouteWithChildren =
  ProtectedPositionsIdRoute._addFileChildren(ProtectedPositionsIdRouteChildren)

interface ProtectedPositionsRouteChildren {
  ProtectedPositionsIdRoute: typeof ProtectedPositionsIdRouteWithChildren
  ProtectedPositionsPositionIdRoute: typeof ProtectedPositionsPositionIdRoute
  ProtectedPositionsIndexRoute: typeof ProtectedPositionsIndexRoute
}

const ProtectedPositionsRouteChildren: ProtectedPositionsRouteChildren = {
  ProtectedPositionsIdRoute: ProtectedPositionsIdRouteWithChildren,
  ProtectedPositionsPositionIdRoute: ProtectedPositionsPositionIdRoute,
  ProtectedPositionsIndexRoute: ProtectedPositionsIndexRoute,
}

const ProtectedPositionsRouteWithChildren =
  ProtectedPositionsRoute._addFileChildren(ProtectedPositionsRouteChildren)

interface ProtectedAfterActionsAfterActionIdRouteChildren {
  ProtectedAfterActionsAfterActionIdVersionsRoute: typeof ProtectedAfterActionsAfterActionIdVersionsRoute
}

const ProtectedAfterActionsAfterActionIdRouteChildren: ProtectedAfterActionsAfterActionIdRouteChildren =
  {
    ProtectedAfterActionsAfterActionIdVersionsRoute:
      ProtectedAfterActionsAfterActionIdVersionsRoute,
  }

const ProtectedAfterActionsAfterActionIdRouteWithChildren =
  ProtectedAfterActionsAfterActionIdRoute._addFileChildren(
    ProtectedAfterActionsAfterActionIdRouteChildren,
  )

interface ProtectedEngagementsEngagementIdRouteChildren {
  ProtectedEngagementsEngagementIdAfterActionRoute: typeof ProtectedEngagementsEngagementIdAfterActionRoute
}

const ProtectedEngagementsEngagementIdRouteChildren: ProtectedEngagementsEngagementIdRouteChildren =
  {
    ProtectedEngagementsEngagementIdAfterActionRoute:
      ProtectedEngagementsEngagementIdAfterActionRoute,
  }

const ProtectedEngagementsEngagementIdRouteWithChildren =
  ProtectedEngagementsEngagementIdRoute._addFileChildren(
    ProtectedEngagementsEngagementIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAccessibilityRoute: typeof ProtectedAccessibilityRoute
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedBriefsRoute: typeof ProtectedBriefsRoute
  ProtectedCalendarRoute: typeof ProtectedCalendarRouteWithChildren
  ProtectedContactsRoute: typeof ProtectedContactsRouteWithChildren
  ProtectedCountriesRoute: typeof ProtectedCountriesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDataLibraryRoute: typeof ProtectedDataLibraryRoute
  ProtectedEventsRoute: typeof ProtectedEventsRoute
  ProtectedExportRoute: typeof ProtectedExportRoute
  ProtectedForumsRoute: typeof ProtectedForumsRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedIntakeRoute: typeof ProtectedIntakeRouteWithChildren
  ProtectedIntelligenceRoute: typeof ProtectedIntelligenceRoute
  ProtectedModernNavDemoRoute: typeof ProtectedModernNavDemoRoute
  ProtectedMonitoringRoute: typeof ProtectedMonitoringRoute
  ProtectedMousRoute: typeof ProtectedMousRoute
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRoute
  ProtectedPersonsRoute: typeof ProtectedPersonsRoute
  ProtectedPositionsRoute: typeof ProtectedPositionsRouteWithChildren
  ProtectedPrototypeDossierRoute: typeof ProtectedPrototypeDossierRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedResponsiveDemoRoute: typeof ProtectedResponsiveDemoRoute
  ProtectedSearchRoute: typeof ProtectedSearchRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedThemesRoute: typeof ProtectedThemesRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedWordAssistantRoute: typeof ProtectedWordAssistantRoute
  ProtectedWorkingGroupsRoute: typeof ProtectedWorkingGroupsRoute
  ProtectedAdminApprovalsRoute: typeof ProtectedAdminApprovalsRoute
  ProtectedAfterActionsAfterActionIdRoute: typeof ProtectedAfterActionsAfterActionIdRouteWithChildren
  ProtectedDossiersIdRoute: typeof ProtectedDossiersIdRoute
  ProtectedEngagementsEngagementIdRoute: typeof ProtectedEngagementsEngagementIdRouteWithChildren
  ProtectedMyWorkAssignmentsRoute: typeof ProtectedMyWorkAssignmentsRoute
  ProtectedMyWorkIntakeRoute: typeof ProtectedMyWorkIntakeRoute
  ProtectedMyWorkWaitingRoute: typeof ProtectedMyWorkWaitingRoute
  ProtectedRelationshipsGraphRoute: typeof ProtectedRelationshipsGraphRoute
  ProtectedTasksIdRoute: typeof ProtectedTasksIdRoute
  ProtectedTasksEscalationsRoute: typeof ProtectedTasksEscalationsRoute
  ProtectedTasksQueueRoute: typeof ProtectedTasksQueueRoute
  ProtectedAfterActionsIndexRoute: typeof ProtectedAfterActionsIndexRoute
  ProtectedApprovalsIndexRoute: typeof ProtectedApprovalsIndexRoute
  ProtectedDossiersIndexRoute: typeof ProtectedDossiersIndexRoute
  ProtectedEngagementsIndexRoute: typeof ProtectedEngagementsIndexRoute
  ProtectedTasksIndexRoute: typeof ProtectedTasksIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccessibilityRoute: ProtectedAccessibilityRoute,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedBriefsRoute: ProtectedBriefsRoute,
  ProtectedCalendarRoute: ProtectedCalendarRouteWithChildren,
  ProtectedContactsRoute: ProtectedContactsRouteWithChildren,
  ProtectedCountriesRoute: ProtectedCountriesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDataLibraryRoute: ProtectedDataLibraryRoute,
  ProtectedEventsRoute: ProtectedEventsRoute,
  ProtectedExportRoute: ProtectedExportRoute,
  ProtectedForumsRoute: ProtectedForumsRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedIntakeRoute: ProtectedIntakeRouteWithChildren,
  ProtectedIntelligenceRoute: ProtectedIntelligenceRoute,
  ProtectedModernNavDemoRoute: ProtectedModernNavDemoRoute,
  ProtectedMonitoringRoute: ProtectedMonitoringRoute,
  ProtectedMousRoute: ProtectedMousRoute,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRoute,
  ProtectedPersonsRoute: ProtectedPersonsRoute,
  ProtectedPositionsRoute: ProtectedPositionsRouteWithChildren,
  ProtectedPrototypeDossierRoute: ProtectedPrototypeDossierRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedResponsiveDemoRoute: ProtectedResponsiveDemoRoute,
  ProtectedSearchRoute: ProtectedSearchRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedThemesRoute: ProtectedThemesRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedWordAssistantRoute: ProtectedWordAssistantRoute,
  ProtectedWorkingGroupsRoute: ProtectedWorkingGroupsRoute,
  ProtectedAdminApprovalsRoute: ProtectedAdminApprovalsRoute,
  ProtectedAfterActionsAfterActionIdRoute:
    ProtectedAfterActionsAfterActionIdRouteWithChildren,
  ProtectedDossiersIdRoute: ProtectedDossiersIdRoute,
  ProtectedEngagementsEngagementIdRoute:
    ProtectedEngagementsEngagementIdRouteWithChildren,
  ProtectedMyWorkAssignmentsRoute: ProtectedMyWorkAssignmentsRoute,
  ProtectedMyWorkIntakeRoute: ProtectedMyWorkIntakeRoute,
  ProtectedMyWorkWaitingRoute: ProtectedMyWorkWaitingRoute,
  ProtectedRelationshipsGraphRoute: ProtectedRelationshipsGraphRoute,
  ProtectedTasksIdRoute: ProtectedTasksIdRoute,
  ProtectedTasksEscalationsRoute: ProtectedTasksEscalationsRoute,
  ProtectedTasksQueueRoute: ProtectedTasksQueueRoute,
  ProtectedAfterActionsIndexRoute: ProtectedAfterActionsIndexRoute,
  ProtectedApprovalsIndexRoute: ProtectedApprovalsIndexRoute,
  ProtectedDossiersIndexRoute: ProtectedDossiersIndexRoute,
  ProtectedEngagementsIndexRoute: ProtectedEngagementsIndexRoute,
  ProtectedTasksIndexRoute: ProtectedTasksIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ModernNavStandaloneRoute: ModernNavStandaloneRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
