-- Migration: Create Briefs Table
-- Date: 2025-09-30
-- Task: T009

-- Create briefs table
CREATE TABLE briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dossier_id UUID NOT NULL REFERENCES dossiers(id) ON DELETE CASCADE,

  -- Bilingual content (JSONB for structured sections)
  content_en JSONB NOT NULL CHECK (
    content_en ? 'summary' AND 
    content_en ? 'sections'
  ),
  content_ar JSONB NOT NULL CHECK (
    content_ar ? 'summary' AND 
    content_ar ? 'sections'
  ),

  -- Metadata
  date_range_start TIMESTAMP WITH TIME ZONE,
  date_range_end TIMESTAMP WITH TIME ZONE,
  generated_by TEXT NOT NULL CHECK (generated_by IN ('ai', 'manual')),
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  generated_by_user_id UUID REFERENCES auth.users(id),

  -- Template flag
  is_template BOOLEAN DEFAULT FALSE,

  -- Constraint: date range validation
  CONSTRAINT valid_date_range CHECK (
    date_range_start IS NULL OR 
    date_range_end IS NULL OR 
    date_range_start <= date_range_end
  )
);

-- Indexes
CREATE INDEX idx_briefs_dossier ON briefs(dossier_id);
CREATE INDEX idx_briefs_generated_at ON briefs(generated_at DESC);
CREATE INDEX idx_briefs_generated_by ON briefs(generated_by);
CREATE INDEX idx_briefs_template ON briefs(is_template) WHERE is_template = true;

-- GIN index for JSONB content search (optional, for future enhancements)
CREATE INDEX idx_briefs_content_en ON briefs USING GIN(content_en);
CREATE INDEX idx_briefs_content_ar ON briefs USING GIN(content_ar);

-- Enable RLS
ALTER TABLE briefs ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- View: Inherit from dossier permissions
CREATE POLICY "view_briefs_via_dossier"
ON briefs FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM dossiers
    WHERE id = dossier_id
    AND get_user_clearance_level(auth.uid()) >=
      CASE sensitivity_level 
        WHEN 'low' THEN 1 
        WHEN 'medium' THEN 2 
        WHEN 'high' THEN 3 
      END
  )
);

-- Insert: Users who can edit dossier can create briefs
CREATE POLICY "create_briefs_via_dossier_edit"
ON briefs FOR INSERT
TO authenticated
WITH CHECK (can_edit_dossier(dossier_id));

-- Briefs are immutable after creation (no UPDATE or DELETE policies)

-- Comments
COMMENT ON TABLE briefs IS 'Executive briefs for dossiers - generated by AI or manually created';
COMMENT ON COLUMN briefs.content_en IS 'English content as JSONB with structure: {summary, sections}';
COMMENT ON COLUMN briefs.content_ar IS 'Arabic content as JSONB with structure: {summary, sections}';
COMMENT ON COLUMN briefs.generated_by IS 'Source: ai (AnythingLLM) or manual (user-created)';
COMMENT ON COLUMN briefs.is_template IS 'Flag for template briefs used as fallback';
COMMENT ON COLUMN briefs.date_range_start IS 'Start of period covered by brief';
COMMENT ON COLUMN briefs.date_range_end IS 'End of period covered by brief';
