-- Migration: Multi-Language Content System
-- Feature: Multi-language content authoring and storage
-- Date: 2026-01-12
-- Description: Enables entities to be authored and stored in multiple languages
-- with support for Arabic, English, French, and other diplomatic languages

-- ============================================================================
-- SUPPORTED LANGUAGES
-- ============================================================================

-- Create enum for supported content languages
CREATE TYPE content_language AS ENUM (
  'ar',  -- Arabic (RTL)
  'en',  -- English
  'fr',  -- French
  'es',  -- Spanish
  'zh',  -- Chinese
  'ru',  -- Russian (UN official languages)
  'pt',  -- Portuguese
  'de',  -- German
  'it',  -- Italian
  'ja',  -- Japanese
  'ko',  -- Korean
  'tr',  -- Turkish
  'fa',  -- Persian/Farsi (RTL)
  'ur',  -- Urdu (RTL)
  'hi'   -- Hindi
);

-- RTL languages reference
COMMENT ON TYPE content_language IS 'Supported content languages. RTL languages: ar, fa, ur';

-- ============================================================================
-- ENTITY CONTENT TRANSLATIONS TABLE
-- ============================================================================

-- Main table for storing multi-language content for entities
CREATE TABLE entity_content_translations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Entity reference (polymorphic)
  entity_type TEXT NOT NULL CHECK (entity_type IN (
    'dossier', 'brief', 'position', 'commitment', 'mou',
    'calendar_entry', 'document', 'engagement', 'forum',
    'working_group', 'intelligence_signal'
  )),
  entity_id UUID NOT NULL,

  -- Content identification
  field_name TEXT NOT NULL CHECK (field_name <> ''),
  language content_language NOT NULL,

  -- Content storage
  content TEXT NOT NULL,
  content_format TEXT NOT NULL DEFAULT 'plain' CHECK (content_format IN ('plain', 'html', 'markdown', 'json')),

  -- Translation metadata
  is_primary BOOLEAN NOT NULL DEFAULT false,
  is_machine_translated BOOLEAN NOT NULL DEFAULT false,
  translation_confidence DECIMAL(3,2) CHECK (translation_confidence >= 0 AND translation_confidence <= 1),
  source_language content_language,

  -- Versioning & review
  version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'approved', 'published')),
  reviewed_by UUID REFERENCES auth.users(id),
  reviewed_at TIMESTAMPTZ,

  -- Audit trail
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  updated_by UUID REFERENCES auth.users(id),

  -- Unique constraint: one translation per entity+field+language
  CONSTRAINT unique_entity_field_language UNIQUE (entity_type, entity_id, field_name, language)
);

-- Add comments
COMMENT ON TABLE entity_content_translations IS 'Multi-language content storage for all entities';
COMMENT ON COLUMN entity_content_translations.entity_type IS 'Type of entity (dossier, brief, position, etc.)';
COMMENT ON COLUMN entity_content_translations.field_name IS 'Name of the field being translated (name, description, summary, etc.)';
COMMENT ON COLUMN entity_content_translations.is_primary IS 'Whether this is the primary/authoritative translation';
COMMENT ON COLUMN entity_content_translations.is_machine_translated IS 'Whether this was generated by AI translation';
COMMENT ON COLUMN entity_content_translations.translation_confidence IS 'AI translation confidence score (0-1)';
COMMENT ON COLUMN entity_content_translations.source_language IS 'Language this was translated from (null if original)';
COMMENT ON COLUMN entity_content_translations.content_format IS 'Format of content: plain text, HTML, Markdown, or JSON';

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Primary lookup index
CREATE INDEX idx_entity_content_entity ON entity_content_translations(entity_type, entity_id);

-- Language filtering
CREATE INDEX idx_entity_content_language ON entity_content_translations(language);

-- Field name lookup
CREATE INDEX idx_entity_content_field ON entity_content_translations(field_name);

-- Primary content lookup
CREATE INDEX idx_entity_content_primary ON entity_content_translations(entity_type, entity_id, is_primary) WHERE is_primary = true;

-- Status filtering
CREATE INDEX idx_entity_content_status ON entity_content_translations(status);

-- Full-text search on content
CREATE INDEX idx_entity_content_search ON entity_content_translations USING GIN(to_tsvector('simple', content));

-- Updated timestamp for sync
CREATE INDEX idx_entity_content_updated ON entity_content_translations(updated_at DESC);

-- ============================================================================
-- ENTITY LANGUAGE PREFERENCES
-- ============================================================================

-- Track which languages are available for each entity
CREATE TABLE entity_language_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Entity reference
  entity_type TEXT NOT NULL,
  entity_id UUID NOT NULL,

  -- Language settings
  primary_language content_language NOT NULL DEFAULT 'en',
  available_languages content_language[] NOT NULL DEFAULT ARRAY['en'::content_language],
  auto_translate BOOLEAN NOT NULL DEFAULT false,
  auto_translate_to content_language[] DEFAULT ARRAY[]::content_language[],

  -- Audit trail
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  updated_by UUID REFERENCES auth.users(id),

  -- Unique constraint
  CONSTRAINT unique_entity_language_settings UNIQUE (entity_type, entity_id)
);

COMMENT ON TABLE entity_language_settings IS 'Language configuration for each entity';
COMMENT ON COLUMN entity_language_settings.primary_language IS 'The primary/authoritative language for this entity';
COMMENT ON COLUMN entity_language_settings.available_languages IS 'Languages that have content for this entity';
COMMENT ON COLUMN entity_language_settings.auto_translate IS 'Whether to auto-translate when primary content changes';
COMMENT ON COLUMN entity_language_settings.auto_translate_to IS 'Target languages for auto-translation';

CREATE INDEX idx_entity_lang_settings_entity ON entity_language_settings(entity_type, entity_id);

-- ============================================================================
-- LANGUAGE METADATA TABLE
-- ============================================================================

-- Metadata about supported languages (for UI display)
CREATE TABLE supported_languages (
  code content_language PRIMARY KEY,
  name_en TEXT NOT NULL,
  name_native TEXT NOT NULL,
  is_rtl BOOLEAN NOT NULL DEFAULT false,
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  display_order INTEGER NOT NULL DEFAULT 100,
  flag_emoji TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Insert supported languages
INSERT INTO supported_languages (code, name_en, name_native, is_rtl, is_enabled, display_order, flag_emoji) VALUES
  ('ar', 'Arabic', 'العربية', true, true, 1, '🇸🇦'),
  ('en', 'English', 'English', false, true, 2, '🇬🇧'),
  ('fr', 'French', 'Français', false, true, 3, '🇫🇷'),
  ('es', 'Spanish', 'Español', false, true, 4, '🇪🇸'),
  ('zh', 'Chinese', '中文', false, true, 5, '🇨🇳'),
  ('ru', 'Russian', 'Русский', false, true, 6, '🇷🇺'),
  ('pt', 'Portuguese', 'Português', false, false, 7, '🇵🇹'),
  ('de', 'German', 'Deutsch', false, false, 8, '🇩🇪'),
  ('it', 'Italian', 'Italiano', false, false, 9, '🇮🇹'),
  ('ja', 'Japanese', '日本語', false, false, 10, '🇯🇵'),
  ('ko', 'Korean', '한국어', false, false, 11, '🇰🇷'),
  ('tr', 'Turkish', 'Türkçe', false, false, 12, '🇹🇷'),
  ('fa', 'Persian', 'فارسی', true, false, 13, '🇮🇷'),
  ('ur', 'Urdu', 'اردو', true, false, 14, '🇵🇰'),
  ('hi', 'Hindi', 'हिन्दी', false, false, 15, '🇮🇳');

COMMENT ON TABLE supported_languages IS 'Metadata about supported content languages';

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger to update updated_at timestamp
CREATE TRIGGER update_entity_content_translations_updated_at
  BEFORE UPDATE ON entity_content_translations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_entity_language_settings_updated_at
  BEFORE UPDATE ON entity_language_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- RPC FUNCTIONS
-- ============================================================================

-- Get all translations for an entity
CREATE OR REPLACE FUNCTION get_entity_translations(
  p_entity_type TEXT,
  p_entity_id UUID,
  p_language content_language DEFAULT NULL
)
RETURNS TABLE (
  id UUID,
  field_name TEXT,
  language content_language,
  content TEXT,
  content_format TEXT,
  is_primary BOOLEAN,
  is_machine_translated BOOLEAN,
  translation_confidence DECIMAL,
  status TEXT,
  version INTEGER,
  updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ect.id,
    ect.field_name,
    ect.language,
    ect.content,
    ect.content_format,
    ect.is_primary,
    ect.is_machine_translated,
    ect.translation_confidence,
    ect.status,
    ect.version,
    ect.updated_at
  FROM entity_content_translations ect
  WHERE ect.entity_type = p_entity_type
    AND ect.entity_id = p_entity_id
    AND (p_language IS NULL OR ect.language = p_language)
  ORDER BY ect.field_name, ect.language;
END;
$$;

-- Get content for a specific field in a specific language (with fallback)
CREATE OR REPLACE FUNCTION get_entity_content(
  p_entity_type TEXT,
  p_entity_id UUID,
  p_field_name TEXT,
  p_language content_language,
  p_fallback_language content_language DEFAULT 'en'
)
RETURNS TABLE (
  content TEXT,
  language content_language,
  is_fallback BOOLEAN,
  is_machine_translated BOOLEAN,
  translation_confidence DECIMAL
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Try requested language first
  RETURN QUERY
  SELECT
    ect.content,
    ect.language,
    false AS is_fallback,
    ect.is_machine_translated,
    ect.translation_confidence
  FROM entity_content_translations ect
  WHERE ect.entity_type = p_entity_type
    AND ect.entity_id = p_entity_id
    AND ect.field_name = p_field_name
    AND ect.language = p_language
    AND ect.status IN ('approved', 'published')
  LIMIT 1;

  -- If found, return
  IF FOUND THEN
    RETURN;
  END IF;

  -- Try fallback language
  RETURN QUERY
  SELECT
    ect.content,
    ect.language,
    true AS is_fallback,
    ect.is_machine_translated,
    ect.translation_confidence
  FROM entity_content_translations ect
  WHERE ect.entity_type = p_entity_type
    AND ect.entity_id = p_entity_id
    AND ect.field_name = p_field_name
    AND ect.language = p_fallback_language
    AND ect.status IN ('approved', 'published')
  LIMIT 1;

  -- If found, return
  IF FOUND THEN
    RETURN;
  END IF;

  -- Try primary language
  RETURN QUERY
  SELECT
    ect.content,
    ect.language,
    true AS is_fallback,
    ect.is_machine_translated,
    ect.translation_confidence
  FROM entity_content_translations ect
  WHERE ect.entity_type = p_entity_type
    AND ect.entity_id = p_entity_id
    AND ect.field_name = p_field_name
    AND ect.is_primary = true
  LIMIT 1;
END;
$$;

-- Upsert translation content
CREATE OR REPLACE FUNCTION upsert_entity_translation(
  p_entity_type TEXT,
  p_entity_id UUID,
  p_field_name TEXT,
  p_language content_language,
  p_content TEXT,
  p_content_format TEXT DEFAULT 'plain',
  p_is_primary BOOLEAN DEFAULT false,
  p_is_machine_translated BOOLEAN DEFAULT false,
  p_translation_confidence DECIMAL DEFAULT NULL,
  p_source_language content_language DEFAULT NULL,
  p_status TEXT DEFAULT 'draft'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_translation_id UUID;
  v_current_version INTEGER;
BEGIN
  -- Get current version if exists
  SELECT version INTO v_current_version
  FROM entity_content_translations
  WHERE entity_type = p_entity_type
    AND entity_id = p_entity_id
    AND field_name = p_field_name
    AND language = p_language;

  -- Upsert the translation
  INSERT INTO entity_content_translations (
    entity_type,
    entity_id,
    field_name,
    language,
    content,
    content_format,
    is_primary,
    is_machine_translated,
    translation_confidence,
    source_language,
    status,
    version,
    created_by,
    updated_by
  ) VALUES (
    p_entity_type,
    p_entity_id,
    p_field_name,
    p_language,
    p_content,
    p_content_format,
    p_is_primary,
    p_is_machine_translated,
    p_translation_confidence,
    p_source_language,
    p_status,
    COALESCE(v_current_version, 0) + 1,
    v_user_id,
    v_user_id
  )
  ON CONFLICT (entity_type, entity_id, field_name, language)
  DO UPDATE SET
    content = EXCLUDED.content,
    content_format = EXCLUDED.content_format,
    is_primary = EXCLUDED.is_primary,
    is_machine_translated = EXCLUDED.is_machine_translated,
    translation_confidence = EXCLUDED.translation_confidence,
    source_language = EXCLUDED.source_language,
    status = EXCLUDED.status,
    version = entity_content_translations.version + 1,
    updated_by = v_user_id,
    updated_at = now()
  RETURNING id INTO v_translation_id;

  -- Update entity language settings
  INSERT INTO entity_language_settings (entity_type, entity_id, available_languages, primary_language, created_by, updated_by)
  VALUES (p_entity_type, p_entity_id, ARRAY[p_language], p_language, v_user_id, v_user_id)
  ON CONFLICT (entity_type, entity_id)
  DO UPDATE SET
    available_languages = ARRAY(
      SELECT DISTINCT unnest(entity_language_settings.available_languages || ARRAY[p_language])
    ),
    primary_language = CASE
      WHEN p_is_primary THEN p_language
      ELSE entity_language_settings.primary_language
    END,
    updated_by = v_user_id,
    updated_at = now();

  RETURN v_translation_id;
END;
$$;

-- Get available languages for an entity
CREATE OR REPLACE FUNCTION get_entity_available_languages(
  p_entity_type TEXT,
  p_entity_id UUID
)
RETURNS TABLE (
  language content_language,
  name_en TEXT,
  name_native TEXT,
  is_rtl BOOLEAN,
  is_primary BOOLEAN,
  field_count BIGINT,
  last_updated TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    sl.code AS language,
    sl.name_en,
    sl.name_native,
    sl.is_rtl,
    COALESCE(els.primary_language = sl.code, false) AS is_primary,
    COUNT(ect.id) AS field_count,
    MAX(ect.updated_at) AS last_updated
  FROM supported_languages sl
  LEFT JOIN entity_content_translations ect
    ON ect.language = sl.code
    AND ect.entity_type = p_entity_type
    AND ect.entity_id = p_entity_id
  LEFT JOIN entity_language_settings els
    ON els.entity_type = p_entity_type
    AND els.entity_id = p_entity_id
  WHERE sl.is_enabled = true
  GROUP BY sl.code, sl.name_en, sl.name_native, sl.is_rtl, sl.display_order, els.primary_language
  HAVING COUNT(ect.id) > 0 OR sl.code IN ('ar', 'en') -- Always show Arabic and English
  ORDER BY
    CASE WHEN COALESCE(els.primary_language = sl.code, false) THEN 0 ELSE 1 END,
    sl.display_order;
END;
$$;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE entity_content_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE entity_language_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE supported_languages ENABLE ROW LEVEL SECURITY;

-- Supported languages are readable by all authenticated users
CREATE POLICY "supported_languages_read"
ON supported_languages FOR SELECT
TO authenticated
USING (true);

-- Entity content translations policies
CREATE POLICY "entity_content_translations_select"
ON entity_content_translations FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "entity_content_translations_insert"
ON entity_content_translations FOR INSERT
TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "entity_content_translations_update"
ON entity_content_translations FOR UPDATE
TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "entity_content_translations_delete"
ON entity_content_translations FOR DELETE
TO authenticated
USING (created_by = auth.uid() OR EXISTS (
  SELECT 1 FROM auth.users u
  WHERE u.id = auth.uid()
  AND u.raw_user_meta_data->>'role' IN ('admin', 'manager')
));

-- Entity language settings policies
CREATE POLICY "entity_language_settings_select"
ON entity_language_settings FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "entity_language_settings_insert"
ON entity_language_settings FOR INSERT
TO authenticated
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "entity_language_settings_update"
ON entity_language_settings FOR UPDATE
TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT USAGE ON TYPE content_language TO authenticated;
GRANT SELECT ON supported_languages TO authenticated;
GRANT ALL ON entity_content_translations TO authenticated;
GRANT ALL ON entity_language_settings TO authenticated;
GRANT EXECUTE ON FUNCTION get_entity_translations TO authenticated;
GRANT EXECUTE ON FUNCTION get_entity_content TO authenticated;
GRANT EXECUTE ON FUNCTION upsert_entity_translation TO authenticated;
GRANT EXECUTE ON FUNCTION get_entity_available_languages TO authenticated;

-- ============================================================================
-- MIGRATION HELPER: Migrate existing _en/_ar content to new system
-- ============================================================================

-- This function can be called to migrate existing bilingual content
CREATE OR REPLACE FUNCTION migrate_dossier_bilingual_content(p_dossier_id UUID DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count INTEGER := 0;
  v_dossier RECORD;
BEGIN
  FOR v_dossier IN
    SELECT id, name_en, name_ar, description_en, description_ar, created_by
    FROM dossiers
    WHERE (p_dossier_id IS NULL OR id = p_dossier_id)
      AND (name_en IS NOT NULL OR name_ar IS NOT NULL)
  LOOP
    -- Migrate English name
    IF v_dossier.name_en IS NOT NULL AND v_dossier.name_en <> '' THEN
      INSERT INTO entity_content_translations (
        entity_type, entity_id, field_name, language, content, is_primary, status, created_by, updated_by
      ) VALUES (
        'dossier', v_dossier.id, 'name', 'en', v_dossier.name_en, true, 'published', v_dossier.created_by, v_dossier.created_by
      ) ON CONFLICT (entity_type, entity_id, field_name, language) DO NOTHING;
      v_count := v_count + 1;
    END IF;

    -- Migrate Arabic name
    IF v_dossier.name_ar IS NOT NULL AND v_dossier.name_ar <> '' THEN
      INSERT INTO entity_content_translations (
        entity_type, entity_id, field_name, language, content, is_primary, status, created_by, updated_by
      ) VALUES (
        'dossier', v_dossier.id, 'name', 'ar', v_dossier.name_ar, false, 'published', v_dossier.created_by, v_dossier.created_by
      ) ON CONFLICT (entity_type, entity_id, field_name, language) DO NOTHING;
      v_count := v_count + 1;
    END IF;

    -- Migrate English description
    IF v_dossier.description_en IS NOT NULL AND v_dossier.description_en <> '' THEN
      INSERT INTO entity_content_translations (
        entity_type, entity_id, field_name, language, content, is_primary, status, created_by, updated_by
      ) VALUES (
        'dossier', v_dossier.id, 'description', 'en', v_dossier.description_en, true, 'published', v_dossier.created_by, v_dossier.created_by
      ) ON CONFLICT (entity_type, entity_id, field_name, language) DO NOTHING;
      v_count := v_count + 1;
    END IF;

    -- Migrate Arabic description
    IF v_dossier.description_ar IS NOT NULL AND v_dossier.description_ar <> '' THEN
      INSERT INTO entity_content_translations (
        entity_type, entity_id, field_name, language, content, is_primary, status, created_by, updated_by
      ) VALUES (
        'dossier', v_dossier.id, 'description', 'ar', v_dossier.description_ar, false, 'published', v_dossier.created_by, v_dossier.created_by
      ) ON CONFLICT (entity_type, entity_id, field_name, language) DO NOTHING;
      v_count := v_count + 1;
    END IF;

    -- Update entity language settings
    INSERT INTO entity_language_settings (
      entity_type, entity_id, primary_language, available_languages, created_by, updated_by
    ) VALUES (
      'dossier', v_dossier.id, 'en', ARRAY['en'::content_language, 'ar'::content_language], v_dossier.created_by, v_dossier.created_by
    ) ON CONFLICT (entity_type, entity_id) DO NOTHING;
  END LOOP;

  RETURN v_count;
END;
$$;

COMMENT ON FUNCTION migrate_dossier_bilingual_content IS 'Migrates existing _en/_ar dossier content to the new multi-language system';
