-- Quick seed: Add sample dossiers for mobile app testing
INSERT INTO dossiers (name_en, name_ar, type, status, sensitivity_level, summary_en, summary_ar, tags) VALUES
('Japan Statistical Partnership', 'شراكة إحصائية مع اليابان', 'country', 'active', 'low',
 'Strategic partnership with Japan Statistics Bureau for data exchange and capacity building',
 'شراكة استراتيجية مع مكتب الإحصاءات الياباني لتبادل البيانات وبناء القدرات',
 ARRAY['partnership', 'data-exchange', 'capacity-building']),
('Germany Cooperation Initiative', 'مبادرة التعاون مع ألمانيا', 'country', 'active', 'low',
 'Cooperation with German Federal Statistical Office on sustainable development indicators',
 'التعاون مع المكتب الاتحادي الألماني للإحصاء حول مؤشرات التنمية المستدامة',
 ARRAY['cooperation', 'sustainability', 'indicators']),
('UN Statistics Division', 'شعبة إحصاءات الأمم المتحدة', 'organization', 'active', 'low',
 'Partnership with UNSD for global statistical standards and methodologies',
 'شراكة مع شعبة إحصاءات الأمم المتحدة للمعايير والمنهجيات الإحصائية العالمية',
 ARRAY['international', 'standards', 'methodology']),
('OECD Statistical Framework', 'الإطار الإحصائي لمنظمة التعاون الاقتصادي والتنمية', 'organization', 'active', 'medium',
 'Collaboration on economic statistics and policy indicators with OECD',
 'التعاون في الإحصاءات الاقتصادية ومؤشرات السياسات مع منظمة التعاون الاقتصادي والتنمية',
 ARRAY['oecd', 'economic-stats', 'policy']),
('World Bank Data Initiative', 'مبادرة بيانات البنك الدولي', 'organization', 'active', 'medium',
 'Joint initiative with World Bank for development statistics and open data',
 'مبادرة مشتركة مع البنك الدولي لإحصاءات التنمية والبيانات المفتوحة',
 ARRAY['world-bank', 'development', 'open-data']),
('GCC Statistical Forum', 'المنتدى الإحصائي لدول مجلس التعاون الخليجي', 'forum', 'active', 'low',
 'Regular forum for GCC countries to harmonize statistical practices',
 'منتدى منتظم لدول مجلس التعاون الخليجي لتنسيق الممارسات الإحصائية',
 ARRAY['gcc', 'harmonization', 'regional']),
('Digital Transformation Theme', 'موضوع التحول الرقمي', 'theme', 'active', 'low',
 'Cross-cutting theme on digital transformation in statistical production',
 'موضوع شامل حول التحول الرقمي في الإنتاج الإحصائي',
 ARRAY['digital', 'transformation', 'innovation'])
ON CONFLICT DO NOTHING;
