/**
 * Country name to ISO 3166-1 alpha-2 code mapping
 * Supports both English and Arabic country names
 */

export const countryCodeMap: Record<string, string> = {
  // GCC Countries
  'saudi arabia': 'sa',
  'المملكة العربية السعودية': 'sa',
  'السعودية': 'sa',
  'uae': 'ae',
  'united arab emirates': 'ae',
  'الإمارات العربية المتحدة': 'ae',
  'الإمارات': 'ae',
  'kuwait': 'kw',
  'الكويت': 'kw',
  'qatar': 'qa',
  'قطر': 'qa',
  'bahrain': 'bh',
  'البحرين': 'bh',
  'oman': 'om',
  'عمان': 'om',
  'سلطنة عمان': 'om',

  // Middle East
  'egypt': 'eg',
  'مصر': 'eg',
  'jordan': 'jo',
  'الأردن': 'jo',
  'lebanon': 'lb',
  'لبنان': 'lb',
  'syria': 'sy',
  'سوريا': 'sy',
  'iraq': 'iq',
  'العراق': 'iq',
  'palestine': 'ps',
  'فلسطين': 'ps',
  'israel': 'il',
  'إسرائيل': 'il',
  'yemen': 'ye',
  'اليمن': 'ye',
  'iran': 'ir',
  'إيران': 'ir',
  'turkey': 'tr',
  'تركيا': 'tr',

  // North Africa
  'morocco': 'ma',
  'المغرب': 'ma',
  'algeria': 'dz',
  'الجزائر': 'dz',
  'tunisia': 'tn',
  'تونس': 'tn',
  'libya': 'ly',
  'ليبيا': 'ly',
  'sudan': 'sd',
  'السودان': 'sd',
  'mauritania': 'mr',
  'موريتانيا': 'mr',

  // Africa
  'south africa': 'za',
  'جنوب أفريقيا': 'za',
  'nigeria': 'ng',
  'نيجيريا': 'ng',
  'kenya': 'ke',
  'كينيا': 'ke',
  'ethiopia': 'et',
  'إثيوبيا': 'et',
  'somalia': 'so',
  'الصومال': 'so',
  'djibouti': 'dj',
  'جيبوتي': 'dj',

  // Asia
  'china': 'cn',
  'الصين': 'cn',
  'japan': 'jp',
  'اليابان': 'jp',
  'south korea': 'kr',
  'كوريا الجنوبية': 'kr',
  'north korea': 'kp',
  'كوريا الشمالية': 'kp',
  'india': 'in',
  'الهند': 'in',
  'pakistan': 'pk',
  'باكستان': 'pk',
  'bangladesh': 'bd',
  'بنغلاديش': 'bd',
  'indonesia': 'id',
  'إندونيسيا': 'id',
  'malaysia': 'my',
  'ماليزيا': 'my',
  'singapore': 'sg',
  'سنغافورة': 'sg',
  'thailand': 'th',
  'تايلاند': 'th',
  'vietnam': 'vn',
  'فيتنام': 'vn',
  'philippines': 'ph',
  'الفلبين': 'ph',

  // Europe
  'united kingdom': 'gb',
  'المملكة المتحدة': 'gb',
  'uk': 'gb',
  'britain': 'gb',
  'بريطانيا': 'gb',
  'france': 'fr',
  'فرنسا': 'fr',
  'germany': 'de',
  'ألمانيا': 'de',
  'italy': 'it',
  'إيطاليا': 'it',
  'spain': 'es',
  'إسبانيا': 'es',
  'netherlands': 'nl',
  'هولندا': 'nl',
  'belgium': 'be',
  'بلجيكا': 'be',
  'switzerland': 'ch',
  'سويسرا': 'ch',
  'austria': 'at',
  'النمسا': 'at',
  'sweden': 'se',
  'السويد': 'se',
  'norway': 'no',
  'النرويج': 'no',
  'denmark': 'dk',
  'الدنمارك': 'dk',
  'finland': 'fi',
  'فنلندا': 'fi',
  'poland': 'pl',
  'بولندا': 'pl',
  'russia': 'ru',
  'روسيا': 'ru',
  'ukraine': 'ua',
  'أوكرانيا': 'ua',
  'greece': 'gr',
  'اليونان': 'gr',
  'portugal': 'pt',
  'البرتغال': 'pt',
  'czech republic': 'cz',
  'التشيك': 'cz',

  // Americas
  'united states': 'us',
  'الولايات المتحدة': 'us',
  'usa': 'us',
  'america': 'us',
  'أمريكا': 'us',
  'canada': 'ca',
  'كندا': 'ca',
  'mexico': 'mx',
  'المكسيك': 'mx',
  'brazil': 'br',
  'البرازيل': 'br',
  'argentina': 'ar',
  'الأرجنتين': 'ar',
  'chile': 'cl',
  'تشيلي': 'cl',
  'colombia': 'co',
  'كولومبيا': 'co',
  'peru': 'pe',
  'بيرو': 'pe',

  // Oceania
  'australia': 'au',
  'أستراليا': 'au',
  'new zealand': 'nz',
  'نيوزيلندا': 'nz',
  'fiji': 'fj',
  'papua new guinea': 'pg',
  'samoa': 'ws',
  'tonga': 'to',
  'vanuatu': 'vu',
  'solomon islands': 'sb',
  'micronesia': 'fm',
  'kiribati': 'ki',
  'marshall islands': 'mh',
  'palau': 'pw',
  'nauru': 'nr',
  'tuvalu': 'tv',

  // Central Asia
  'kazakhstan': 'kz',
  'uzbekistan': 'uz',
  'turkmenistan': 'tm',
  'kyrgyzstan': 'kg',
  'tajikistan': 'tj',
  'afghanistan': 'af',
  'أفغانستان': 'af',

  // Southeast Asia
  'myanmar': 'mm',
  'cambodia': 'kh',
  'laos': 'la',
  'brunei': 'bn',
  'timor-leste': 'tl',
  'east timor': 'tl',

  // South Asia
  'sri lanka': 'lk',
  'nepal': 'np',
  'bhutan': 'bt',
  'maldives': 'mv',

  // East Asia
  'mongolia': 'mn',
  'taiwan': 'tw',
  'hong kong': 'hk',
  'macau': 'mo',

  // Eastern Europe
  'belarus': 'by',
  'moldova': 'md',
  'romania': 'ro',
  'bulgaria': 'bg',
  'hungary': 'hu',
  'slovakia': 'sk',
  'slovenia': 'si',
  'croatia': 'hr',
  'bosnia and herzegovina': 'ba',
  'serbia': 'rs',
  'montenegro': 'me',
  'north macedonia': 'mk',
  'macedonia': 'mk',
  'albania': 'al',
  'kosovo': 'xk',

  // Baltic States
  'estonia': 'ee',
  'latvia': 'lv',
  'lithuania': 'lt',

  // Caucasus
  'georgia': 'ge',
  'armenia': 'am',
  'azerbaijan': 'az',

  // Western Europe
  'ireland': 'ie',
  'luxembourg': 'lu',
  'iceland': 'is',
  'monaco': 'mc',
  'liechtenstein': 'li',
  'andorra': 'ad',
  'san marino': 'sm',
  'vatican city': 'va',
  'malta': 'mt',
  'cyprus': 'cy',

  // Central America & Caribbean
  'guatemala': 'gt',
  'honduras': 'hn',
  'el salvador': 'sv',
  'nicaragua': 'ni',
  'costa rica': 'cr',
  'panama': 'pa',
  'belize': 'bz',
  'cuba': 'cu',
  'jamaica': 'jm',
  'haiti': 'ht',
  'dominican republic': 'do',
  'bahamas': 'bs',
  'trinidad and tobago': 'tt',
  'barbados': 'bb',
  'saint lucia': 'lc',
  'grenada': 'gd',
  'saint vincent and the grenadines': 'vc',
  'antigua and barbuda': 'ag',
  'dominica': 'dm',
  'saint kitts and nevis': 'kn',

  // South America
  'venezuela': 've',
  'ecuador': 'ec',
  'bolivia': 'bo',
  'paraguay': 'py',
  'uruguay': 'uy',
  'guyana': 'gy',
  'suriname': 'sr',
  'french guiana': 'gf',

  // Sub-Saharan Africa
  'ghana': 'gh',
  'senegal': 'sn',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  'cameroon': 'cm',
  'democratic republic of the congo': 'cd',
  'congo': 'cg',
  'republic of the congo': 'cg',
  'angola': 'ao',
  'mozambique': 'mz',
  'madagascar': 'mg',
  'uganda': 'ug',
  'tanzania': 'tz',
  'rwanda': 'rw',
  'burundi': 'bi',
  'zambia': 'zm',
  'zimbabwe': 'zw',
  'malawi': 'mw',
  'botswana': 'bw',
  'namibia': 'na',
  'lesotho': 'ls',
  'eswatini': 'sz',
  'swaziland': 'sz',
  'mali': 'ml',
  'burkina faso': 'bf',
  'niger': 'ne',
  'chad': 'td',
  'central african republic': 'cf',
  'gabon': 'ga',
  'equatorial guinea': 'gq',
  'guinea': 'gn',
  'guinea-bissau': 'gw',
  'sierra leone': 'sl',
  'liberia': 'lr',
  'togo': 'tg',
  'benin': 'bj',
  'eritrea': 'er',
  'south sudan': 'ss',
  'gambia': 'gm',
  'mauritius': 'mu',
  'seychelles': 'sc',
  'comoros': 'km',
  'cape verde': 'cv',
  'sao tome and principe': 'st',

  // Additional UK aliases
  'england': 'gb',
  'scotland': 'gb',
  'wales': 'gb',
  'northern ireland': 'gb',

  // Additional Countries
  'puerto rico': 'pr',
  'greenland': 'gl',
  'faroe islands': 'fo',
  'guam': 'gu',
  'american samoa': 'as',
  'northern mariana islands': 'mp',
  'virgin islands': 'vi',
  'u.s. virgin islands': 'vi',
  'british virgin islands': 'vg',
  'cayman islands': 'ky',
  'bermuda': 'bm',
  'turks and caicos islands': 'tc',
  'anguilla': 'ai',
  'montserrat': 'ms',
  'falkland islands': 'fk',
  'french polynesia': 'pf',
  'new caledonia': 'nc',
  'cook islands': 'ck',
  'niue': 'nu',
  'tokelau': 'tk',
  'wallis and futuna': 'wf',
  'pitcairn islands': 'pn',
  'saint helena': 'sh',
  'reunion': 're',
  'mayotte': 'yt',
  'martinique': 'mq',
  'guadeloupe': 'gp',
  'aruba': 'aw',
  'curacao': 'cw',
  'sint maarten': 'sx',
  'bonaire': 'bq',
  'caribbean netherlands': 'bq',
  'isle of man': 'im',
  'jersey': 'je',
  'guernsey': 'gg',
  'gibraltar': 'gi',
  'aland islands': 'ax',
  'svalbard and jan mayen': 'sj',
  'bouvet island': 'bv',
  'heard island and mcdonald islands': 'hm',
  'christmas island': 'cx',
  'cocos islands': 'cc',
  'norfolk island': 'nf',
  'antarctica': 'aq',
  'french southern territories': 'tf',
  'british indian ocean territory': 'io',
  'western sahara': 'eh',
  'south georgia': 'gs',
  'saint pierre and miquelon': 'pm',
  'saint martin': 'mf',
  'saint barthelemy': 'bl',
};

/**
 * Get ISO 3166-1 alpha-2 country code from country name
 * @param countryName - Country name in English or Arabic
 * @returns ISO country code (lowercase) or null if not found
 */
export function getCountryCode(countryName: string | null | undefined): string | null {
  if (!countryName) return null;

  const normalized = countryName.toLowerCase().trim();
  return countryCodeMap[normalized] || null;
}

/**
 * Check if a country name is valid (has a corresponding code)
 * @param countryName - Country name to validate
 * @returns true if country name maps to a valid code
 */
export function isValidCountry(countryName: string | null | undefined): boolean {
  return getCountryCode(countryName) !== null;
}
